import ServerLogo from '@/app/components/ServerLogo';

const contents = [
  ['overview', 'Overview & server identity'],
  ['facts', 'Reference facts & activity'],
  ['history', 'Launch history & archive record'],
  ['gameplay', 'Baiak map & gameplay loop'],
  ['systems', 'Systems, events & activities'],
  ['pvp', 'PvP, wars & rules to verify'],
  ['client', 'Client & connection safety'],
  ['start', 'How to start & who it suits'],
  ['sources', 'Sources & verification'],
  ['external-links', 'External links'],
];

const facts = [
  ['Server name', 'Baiak Icewar', 'The name is consistent across the archived OT record, directory inventory, and public listing sources.'],
  ['Connection record', 'sv.baiak-icewar.com:7171', 'OpenTibiaList and the local directory inventory show this host and port; confirm the active endpoint before connecting.'],
  ['Archived endpoint', 'baiak-icewar.com:7171', 'OT Archive preserved this earlier host record, which may represent a different edition or period.'],
  ['Client', '8.6 / 8.60', 'Both the archived record and current-style listing identify the classic 8.60 client family.'],
  ['World type', 'Open PvP / PVP', 'The broad classification is published by listing and archive sources; detailed combat rules remain unverified.'],
  ['Region signal', 'Brazil', 'Brazil is shown by the directory listing and archive flag; this does not prove the physical location of every service.'],
  ['Experience', '900× listing; regressive archive table', 'The 900× headline appears in public listing data, while OT Archive describes a regressive experience table.'],
  ['Activity snapshot', '166 online · 1,500 capacity · 246 peak', 'OpenTibiaList values captured on 29 August 2026; these are time-sensitive source measurements, not guarantees.'],
];

const systems = [
  ['Baiak map', 'The archived description presents a heavily edited Baiak map designed around fast movement, compact hunting, and war-oriented encounters.'],
  ['Quests and missions', 'Main quests and missions are named in the archive record, but the current quest list, access requirements, and rewards should be checked in-game or on an operator-maintained guide.'],
  ['Private wars', 'A private war system is part of the historical server description, suggesting organized guild conflict beyond ordinary open-world kills. Current war rules and costs are not published in the reviewed sources.'],
  ['VIP and tasks', 'VIP benefits and task progression are named as core systems. Confirm current bonuses, task reset rules, prices, and account restrictions before spending money.'],
  ['Minigames and bosses', 'Public material references minigames and bosses as repeatable activities that add alternatives to ordinary leveling. Specific encounter mechanics and loot tables remain unverified.'],
  ['Castle 24 and Golden Arena', 'Castle 24 and Golden Arena are named competitive destinations in the archived profile, alongside Safezone and Firestorm Event content.'],
  ['Lottery and events', 'Lottery, automatic events, Firestorm, and other rotating activities are part of the historic feature set; schedules and rewards are likely time-sensitive.'],
];

export default function BaiakIcewarWikiPage() {
  return (
    <main className="cyntara-wiki min-h-screen" data-server-slug="baiak-icewar">
      <header className="cyntara-wiki__header"><h1>Baiak Icewar</h1><small>From OpenTibiaServers Wiki, the primary Open Tibia server directory</small></header>
      <div className="cyntara-wiki__grid">
        <article className="cyntara-wiki__content">
          <div className="flex flex-col gap-6 md:flex-row md:items-start">
            <div className="min-w-0 flex-1">
              <p><strong>Baiak Icewar</strong> is an <strong>Open Tibia server</strong> associated with the classic 8.60 client, a customized Baiak map, <em>Open PvP</em>, and high-rate progression. Its archived description emphasizes a war-oriented world with custom systems, private wars, VIP tasks, minigames, bosses, Castle 24, Safezone, Firestorm, Lottery, and Golden Arena.</p>
              <p>This <strong>Baiak Icewar Wiki profile</strong> separates archived server information from a later public activity snapshot. <u>Players should verify the current client, website, login host, rules, rates, and status before downloading or creating an account</u>, because the operator’s pages were not consistently accessible during research.</p>
            </div>
            <div className="w-full shrink-0 md:w-64"><ServerLogo server={{ name: 'Baiak Icewar', slug: 'baiak-icewar', host: 'sv.baiak-icewar.com' }} size="profile" /></div>
          </div>
          <nav className="cyntara-wiki__toc" aria-label="Table of Contents"><h2>Contents</h2><ol>{contents.map(([id, label]) => <li key={id}><a href={`#${id}`}>{label}</a></li>)}</ol></nav>

          <section id="overview"><SectionHeading>Overview &amp; server identity</SectionHeading><p><strong>Baiak Icewar</strong> belongs to the <em>Baiak OT</em> family of private servers: a compressed, customized world that prioritizes quick access to combat and social activities over the slower geography of a full global map. The archived OT record identifies a custom client, a heavily edited map, and a design aimed primarily at war gameplay.</p><p>The current directory identity points to <code>sv.baiak-icewar.com:7171</code>, Brazil, client 8.6, and PVP. An older OT Archive record uses <code>baiak-icewar.com:7171</code> and attributes the server to Brazil. These may describe separate launch periods or endpoints, so this page intentionally preserves both rather than silently merging them.</p><div className="cyntara-wiki__callout"><strong>Research note</strong><p>“Baiak,” “900×,” and “Open PvP” describe the server’s public positioning, not a complete ruleset. Exact experience stages, item access, protection rules, resets, store terms, and anti-cheat policy require current operator confirmation.</p></div></section>

          <section id="facts"><SectionHeading>Reference facts &amp; activity</SectionHeading><p>The following table combines the most specific archived fields with the separate OpenTibiaList activity snapshot. Snapshot numbers are useful for comparing <a href="/">Open Tibia servers</a>, but they change over time and should not be presented as permanent service facts.</p><div className="cyntara-wiki__table-wrap"><table className="cyntara-wiki__table"><thead><tr><th>Field</th><th>Recorded value</th><th>Evidence &amp; context</th></tr></thead><tbody>{facts.map(([field, value, context]) => <tr key={field}><th>{field}</th><td><strong>{value}</strong></td><td>{context}</td></tr>)}</tbody></table></div><div className="cyntara-wiki__callout"><strong>Rates need reconciliation</strong><p>OpenTibiaList displays 900× experience with 1× loot, skill, magic, and spawn. OT Archive records 900× stages, 20× magic, 10× skill, 5× loot, and a regressive experience table. Because these records are from different contexts, the profile does not choose one as universally current.</p></div></section>

          <section id="history"><SectionHeading>Launch history &amp; archive record</SectionHeading><p>OT Archive preserves an inauguration statement of <strong>15 November 2019 at 15:00</strong>. It also records the phrase “Abriu 16-10” without a year. Those are historical source claims and should not be interpreted as proof of uninterrupted operation, a current season, or a future relaunch date.</p><p>The archive’s technical record lists TFS 1.X, engine version 3, the <code>twist.otbm</code> map, and a reported map size of 20,048 × 20,048. Its description uses promotional language such as “best Baiak,” so those statements are retained as attributed historical wording rather than independent performance guarantees.</p><div className="grid gap-4 md:grid-cols-3"><FactCard label="2019 inauguration" text="15/11/2019 at 15:00 in the archived description." /><FactCard label="8.60 foundation" text="The archived technical profile identifies Tibia 8.6 / 8.60." /><FactCard label="Archive update" text="OT Archive shows a January 2024 record update." /></div></section>

          <section id="gameplay"><SectionHeading>Baiak map &amp; gameplay loop</SectionHeading><p>The defining <strong>Baiak Icewar gameplay</strong> idea is density: a compact custom map, accelerated leveling, and direct access to activities that encourage group formation. The archive’s “mapa voltado para WAR” description makes guild conflict a central design signal, while the task, boss, minigame, and arena references create reasons to keep playing after reaching combat-ready levels.</p><p>Players should expect a progression model that may be materially different from retail Tibia. Do not assume that retail quest order, NPC locations, item prices, vocation balance, or boss mechanics apply. The local <a href="/knowledge">OpenTibiaServers knowledge base</a> can help explain general OT concepts, but the active operator’s rules remain authoritative for this world.</p><div className="cyntara-wiki__callout"><strong>Map guidance</strong><p>The reviewed evidence names the Baiak map and its scale, but does not provide a reliable current route guide. Verify teleports, hunting zones, quest access, protection areas, and event entrances in the active client.</p></div></section>

          <section id="systems"><SectionHeading>Systems, events &amp; activities</SectionHeading><p>The following feature list is based primarily on OT Archive and the independent research record. It is useful for search intent such as <strong>Baiak server features</strong>, but exact implementation may have changed since the archived record.</p><div className="grid gap-4 md:grid-cols-2">{systems.map(([name, detail]) => <div key={name} className="rounded border border-black bg-white p-4"><h3 className="text-base font-bold text-black">{name}</h3><p className="mt-2 text-sm leading-7 text-black">{detail}</p></div>)}</div><p>Public research also associates Baiak Icewar with an integrated Cast system. The referenced official cast page returned a certificate error during retrieval, so current broadcast permissions, spectator limits, and costs remain unverified.</p></section>

          <section id="pvp"><SectionHeading>PvP, wars &amp; rules to verify</SectionHeading><p><strong>Baiak Icewar PvP</strong> is presented as Open PvP with private wars and a war-focused map. That combination may appeal to guilds seeking fast conflict, territory objectives, and organized team play, while solo players should understand that the social and competitive layer can affect progression and safety.</p><p>The sources do not establish current frag thresholds, skull penalties, unjustified-kill limits, death loss, level protection, war declarations, guild limits, multi-client policy, bot rules, or store advantages. <u>Read the current rules before funding an account or joining a war.</u></p><div className="grid gap-4 md:grid-cols-2"><FactCard label="Good fit if" text="You want a compact 8.6 Baiak world with high experience, fast access to PvP, guild activity, bosses, and competitive events." /><FactCard label="Check first" text="Current PvP penalties, war requirements, task resets, VIP benefits, anti-cheat policy, resets, and active event schedule." /></div></section>

          <section id="client"><SectionHeading>Client &amp; connection safety</SectionHeading><p>The current-style listing identifies <code>sv.baiak-icewar.com:7171</code>, while the archive identifies <code>baiak-icewar.com:7171</code>. The historical profile also claims an own/custom client. Because the official website and subpages were access-challenged in research, none of these records should be treated as a current installation instruction without confirmation.</p><ol><li>Begin with the operator-controlled website and verify the account and download domain.</li><li>Confirm the active client version, login host, port, launcher, patch notes, and file checksums.</li><li>Download only from a current official link; do not use reposted clients or disable antivirus protections to force installation.</li><li>Review rules for bots, multi-clienting, account recovery, donations, trading, and PvP before playing.</li><li>Check live population close to your play session because directory data is time-sensitive.</li></ol></section>

          <section id="start"><SectionHeading>How to start &amp; who it suits</SectionHeading><p>Start by comparing the current official instructions with the <a href="/servers/demolidores">Demolidores</a>, <a href="/servers/cyntara">Cyntara</a>, and <a href="/servers/rubinot">RubinOT</a> profiles to understand how different <em>Open Tibia</em> formats handle map scale, PvP, progression, and community systems.</p><ol><li>Confirm whether the active world is still 8.60 and whether the 900× headline is an experience stage or a flat rate.</li><li>Read the latest rules for PvP, private wars, VIP, stores, resets, and automation.</li><li>Verify the current client and endpoint, then create a new account only through the official path.</li><li>Join after checking the current guild and event situation rather than relying on an old launch announcement.</li></ol><p>Baiak Icewar is likely a better fit for players who value fast progression and immediate combat than for players seeking a slow, exploration-heavy real-map experience.</p></section>

          <section id="sources"><SectionHeading>Sources &amp; verification</SectionHeading><p>This profile uses an archived OT Archive record for the historic host, owner field, map, engine, rates, inauguration, and feature description. OpenTibiaList supplies a separate status, activity, ranking, and rate snapshot. The official site and cast-system URL are included for operator verification but were not fully readable in automated research.</p><div className="grid gap-3 md:grid-cols-2"><SourceLink href="https://otarchive.com/server/62cde2f41770eac22ec6ad02" label="OT Archive: Baiak-Icewar record" /><SourceLink href="https://opentibialist.eu/server/baiak-icewar" label="OpenTibiaList: Baiak Icewar listing" /><SourceLink href="https://baiak-icewar.com/" label="Baiak Icewar official domain" /><SourceLink href="https://sv.baiak-icewar.com/?subtopic=castsystem" label="Baiak Icewar Cast system reference" /></div><div className="cyntara-wiki__callout"><strong>Evidence standard</strong><p>Current claims should be supported by an operator-controlled page, dated announcement, or verified live status. Archived records and public directories are valuable discovery references, but their figures and features may become stale.</p></div></section>

          <section id="external-links"><SectionHeading>External links</SectionHeading><ul><li><ExternalLink href="https://baiak-icewar.com/">Official Baiak Icewar domain</ExternalLink></li><li><ExternalLink href="https://opentibialist.eu/server/baiak-icewar">OpenTibiaList server profile</ExternalLink></li><li><ExternalLink href="https://otarchive.com/server/62cde2f41770eac22ec6ad02">OT Archive server record</ExternalLink></li><li><a href="/">OpenTibiaServers directory</a></li><li><a href="/knowledge">OpenTibiaServers knowledge base</a></li><li><a href="/submit-server">Submit updated server information</a></li></ul></section>
        </article>
        <aside className="cyntara-wiki__sidebar"><div className="cyntara-wiki__infobox"><div className="cyntara-wiki__infobox-header">Baiak Icewar</div><ServerLogo server={{ name: 'Baiak Icewar', slug: 'baiak-icewar', host: 'sv.baiak-icewar.com' }} size="profile" /><table><tbody><tr><th>Website</th><td><a href="https://baiak-icewar.com/" target="_blank" rel="nofollow noopener noreferrer">baiak-icewar.com</a></td></tr><tr><th>Host</th><td><code>sv.baiak-icewar.com:7171</code></td></tr><tr><th>Client</th><td>8.6 / 8.60</td></tr><tr><th>World type</th><td>Open PvP / PVP</td></tr><tr><th>Region</th><td>Brazil</td></tr><tr><th>Map</th><td>Custom Baiak</td></tr><tr><th>Experience</th><td>900× listing / regressive archive</td></tr><tr><th>Loot · skill · magic</th><td>1× listing / 5× · 10× · 20× archive</td></tr><tr><th>Capacity</th><td>1,500 listing snapshot</td></tr><tr><th>Peak</th><td>246 listing snapshot</td></tr><tr><th>Status</th><td>Verify current service officially</td></tr></tbody></table></div><div className="cyntara-wiki__callout"><strong>Before downloading</strong><p>Confirm the active client, endpoint, rules, and account path from the operator. Historical and current-style records differ.</p></div><div className="cyntara-wiki__recommended"><h3>Explore the directory</h3><p>Compare Baiak Icewar with other Open Tibia worlds by protocol, PvP type, region, rates, and activity.</p><a className="cyntara-wiki__button" href="/?search=Baiak%20Icewar">Browse similar servers</a></div></aside>
      </div>
    </main>
  );
}

function SectionHeading({ children }) { return <div className="cyntara-wiki__section-heading"><h2>{children}</h2></div>; }
function FactCard({ label, text }) { return <div className="rounded border border-black bg-white p-4"><h3 className="text-base font-bold text-black">{label}</h3><p className="mt-2 text-sm leading-7 text-black">{text}</p></div>; }
function ExternalLink({ href, children }) { return <a href={href} target="_blank" rel="nofollow noopener noreferrer">{children}</a>; }
function SourceLink({ href, label }) { return <a href={href} target="_blank" rel="nofollow noopener noreferrer" className="rounded border border-black bg-white p-4 font-bold hover:no-underline">{label}</a>; }
