import ServerLogo from '@/app/components/ServerLogo';

const contents = [
  ['overview', 'Overview & identity'], ['facts', 'Current and historical facts'], ['progression', 'Rates & progression'],
  ['systems', 'Custom systems & content'], ['pvp', 'PvP, wars & arenas'], ['client', 'Clients, accounts & safety'],
  ['history', 'Launch history'], ['fit', 'Who Gunzodus suits'], ['faq', 'Gunzodus FAQ'], ['sources', 'Sources & verification'], ['links', 'External links'],
];

const facts = [
  ['Server identity', 'Gunzodus real-map Open Tibia server', 'The official Wiki describes a real-map server with custom content, active PvP, castle wars, and guild wars.'],
  ['Historical host', 'gunzodus.net:7171', 'The March 2019 community launch record names this endpoint.'],
  ['Current-style host', 'login.gunzodus.net:7171', 'The official Wiki server bar uses this login host; verify it in the current client instructions.'],
  ['Current profile signal', '15.00 / Retro-PvP / Poland', 'A newer official server-information snapshot labels the project 15.00 Retro-PvP and EU; directory inventory separately reports Poland and 15.2.'],
  ['Historical profile signal', 'Client 10 / 12.00 / France', 'The archived launch record identifies France and client 10, while its title references 14.00+. These are historical records, not a single current specification.'],
  ['Activity snapshot', '551 online on official Wiki capture · 186 directory snapshot', 'Population values are time-sensitive and come from different captures. Neither is a permanent availability guarantee.'],
  ['Progression identity', 'Long-term mid-rate · no-reset positioning', 'Official material describes long-term progression and historical no-reset operation; numerical rates require the current Server Information page.'],
];

const progression = [
  ['Rate label', 'Long-term Mid-Rate', 'The official Server Info page uses this description without publishing complete numeric multipliers in the reviewed extract.'],
  ['Experience', 'Not safely reduced to one number', 'Older third-party research lists staged values, but the official pages reviewed here present the server as long-term mid-rate. Verify current stages before planning a character.'],
  ['Skill and magic', 'Current values not published in the reviewed Wiki index', 'Do not infer rates from the historical client or directory row.'],
  ['Dungeons', 'Bonuses and special monsters', 'The official Dungeon System page documents no-bot hunting areas; exact bonuses, access, and rewards belong to that page.'],
  ['Economy', 'One-time economy reset documented for 17 May 2026', 'The official Wiki names an Old Money system and new economy, but conversion and compensation details require direct verification.'],
];

const systems = [
  ['No-bot Dungeons', 'Special hunting areas such as Nightmare Isles, Marapur Turtles, and Secret Library are presented as no-bot content with special monsters and bonuses. The current client requirement and reward tables should be checked before entering.'],
  ['Soulpit', 'Players use Soul Cores to fight waves of creatures and earn Animus Mastery rewards. Wave structure, difficulty, and exact rewards are not summarized on the Wiki index.'],
  ['World Bosses', "The official list names Morshabaal, Rotrender, The Abomination, Gaz'haragoth, and Ferumbras. Spawn timing, mechanics, loot, and distribution rules remain source-page details."],
  ['Customized Items', 'Gunzodus advertises changed equipment, custom item images, and item descriptions. Check the item guide for names, stats, acquisition routes, and set effects rather than assuming retail values.'],
  ['Bestiary and Charms', 'Bestiary events are part of the rotating bonus system, and the site exposes creature statistics. Charm points, effects, unlocks, and completion rewards need current documentation.'],
  ['Loyalty System', 'The official Wiki lists loyalty bonuses and progression. Thresholds and whether bonuses apply to characters or accounts are not confirmed in the index.'],
  ['Beginner Rewards', 'New players may receive level rewards, beginner equipment, rings, and imbuement scrolls. Exact levels and item lists should be checked on the current reward page.'],
  ['Asylum and custom areas', 'Asylum is documented as a custom city with NPCs, shops, and hunting routes. Access requirements and route guidance should come from the official area guide.'],
];

const links = [
  ['Gunzodus official Wiki', 'https://gunzodus.gunzo.eu/custom/wiki'], ['Server Information', 'https://gunzodus.gunzo.eu/custom/wiki/server_info'],
  ['Dungeon System', 'https://gunzodus.gunzo.eu/custom/wiki/dungeons'], ['Soulpit', 'https://gunzodus.gunzo.eu/custom/wiki/soulpit'],
  ['World Bosses', 'https://gunzodus.gunzo.eu/custom/wiki/world_bosses'], ['Customized Items', 'https://gunzodus.gunzo.eu/custom/wiki/customized_items'],
  ['Private War', 'https://gunzodus.gunzo.eu/custom/wiki/private_war'], ['Global Arena', 'https://gunzodus.gunzo.eu/custom/wiki/global_arena'],
  ['Castle Wars', 'https://gunzodus.gunzo.eu/custom/wiki/castle_wars'], ['Rules', 'https://gunzodus.gunzo.eu/custom/wiki/rules'],
  ['Download Client', 'https://gunzodus.gunzo.eu/custom/wiki/download_client'], ['Official account login', 'https://gunzodus.gunzo.eu/account/login'],
  ['Gunzodus Discord', 'https://discord.gg/3fwcmZr'], ['Gunzodus forum', 'https://forum.gunzodus.net/'],
  ['OpenTibiaServers directory', '/'], ['Knowledge base', '/knowledge'],
];

export default function GunzodusWikiPage() {
  return (
    <main className="cyntara-wiki min-h-screen" data-server-slug="gunzodus">
      <header className="cyntara-wiki__header"><h1>Gunzodus: real-map Open Tibia server, custom systems, dungeons and PvP Wiki</h1><small>From OpenTibiaServers Wiki, the primary Open Tibia server directory</small></header>
      <div className="cyntara-wiki__grid">
        <article className="cyntara-wiki__content">
          <div className="flex flex-col gap-6 md:flex-row md:items-start"><div className="min-w-0 flex-1"><p><strong>Gunzodus</strong> is a long-running <strong>Open Tibia server</strong> built around a real-map experience, custom items, active <em>Retro-PvP</em>, guild and castle wars, dungeons, world bosses, Bestiary, Charms, and a broad official Wiki. It is commonly searched by players looking for a mid-rate real map with custom content rather than a plain retail clone.</p><p>This <strong>Gunzodus Wiki profile</strong> separates the current official information layer from older launch and directory snapshots. <u>Verify the active login host, client, rates, rules, and download package on the official site before installing or funding an account.</u></p></div><div className="w-full shrink-0 md:w-64"><ServerLogo server={{ name: 'Gunzodus', slug: 'gunzodus', host: 'login.gunzodus.net' }} size="profile" /></div></div>
          <nav className="cyntara-wiki__toc" aria-label="Table of contents"><h2>Contents</h2><ol>{contents.map(([id, label]) => <li key={id}><a href={`#${id}`}>{label}</a></li>)}</ol></nav>

          <section id="overview"><SectionHeading>Overview &amp; identity</SectionHeading><p>The official Gunzodus Wiki presents a server with a real map, custom content, active PvP, castle wars, and guild wars. That foundation is expanded with named systems such as no-bot dungeons, Soulpit, world bosses, customized items, loyalty, beginner rewards, and rotating weekend bonuses.</p><p>Gunzodus is also a useful example of why a server directory needs dates and provenance. A 2019 launch record points to <code>gunzodus.net:7171</code>, client 10, and France; newer official material uses <code>login.gunzodus.net:7171</code>, describes an EU Retro-PvP server, and displays 15.00-era information. These records may represent different client generations or service phases.</p><div className="cyntara-wiki__callout"><strong>Current-status note</strong><p>The official website and public directory do not expose one perfectly consistent snapshot in every source. This page keeps historical and current-style signals distinct so “Gunzodus server” searches lead to useful context without overstating certainty.</p></div></section>

          <section id="facts"><SectionHeading>Current and historical facts</SectionHeading><p>Use this table as a research reference, not as a substitute for the live operator pages. Player counts, client labels, hostnames, and country signals can change independently.</p><DataTable headers={['Field', 'Recorded value', 'Evidence & context']} rows={facts} /></section>

          <section id="progression"><SectionHeading>Rates &amp; progression</SectionHeading><p><strong>Gunzodus rates</strong> are described by the official source as <em>Long-term Mid-Rate</em>, but the Wiki index does not expose a complete numerical table. That label implies a more sustained character journey than a high-EXP EVO server. It should not be replaced with historical or third-party numbers without checking the current Server Information page.</p><DataTable headers={['Category', 'Recorded value', 'Player context']} rows={progression} /><div className="cyntara-wiki__callout"><strong>Do not guess the rate table</strong><p>Confirm EXP, skill, magic, loot, spawn, stamina, and any latest-client bonus before comparing Gunzodus with other <a href="/">Open Tibia servers</a>. The official material references multiple client generations and seasonal bonuses.</p></div></section>

          <section id="systems"><SectionHeading>Custom systems &amp; content</SectionHeading><p>The following <strong>Gunzodus features</strong> are named by the official Wiki. Each item links to a deeper source where available; exact requirements, rewards, and live availability remain subject to operator updates.</p><div className="grid gap-4 md:grid-cols-2">{systems.map(([name, detail]) => <FactCard key={name} label={name} text={detail} />)}</div><p>Additional official topics include shortened quests, Quick Loot, commands, character auctions, private shops, and the 2026 economy reset. The safest interpretation is that Gunzodus has a large custom documentation surface, while each subsystem needs its own current rules.</p></section>

          <section id="pvp"><SectionHeading>PvP, wars &amp; arenas</SectionHeading><p><strong>Gunzodus PvP</strong> is presented as active Retro-PvP. The official explanation says the older PvP system can make players skulled when using area-of-effect spells or runes. Competitive content includes <em>Private War</em>, Guild Wars, Castle Wars, and Global Arena.</p><div className="grid gap-4 md:grid-cols-2"><FactCard label="Private War" text="Guild battle content is available in designated arenas. Team sizes, costs, duration, victory conditions, and rewards need the current official rule page." /><FactCard label="Castle Wars" text="The Wiki lists castle-war content and names Outlaw Castle and Castle of Greenshore in its current presentation. Capture rules and benefits are not inferred here." /><FactCard label="Global Arena" text="A PvP area combines familiar towns such as Edron, Yalahar, Darashia, and Liberty Bay. Access and matchmaking details should be verified in the official guide." /><FactCard label="PvP boundaries" text="Skull, frag, protection, multi-client, and event restrictions are not fully summarized by the Wiki index. Read the active rules before joining conflict." /></div></section>

          <section id="client"><SectionHeading>Clients, accounts &amp; connection safety</SectionHeading><p>The official Wiki provides updated Gunzodus 10 and Gunzodus 12 Windows client links and separately references a 15.00 Retro-PvP experience. Older announcement text mentions 10+ and 15.00 support. Because these labels differ across pages, <u>use the current official download route and confirm the supported client before logging in</u>.</p><ol><li>Start with the official <a href="https://gunzodus.gunzo.eu/custom/wiki/download_client" target="_blank" rel="nofollow noopener noreferrer">Download Client</a> page.</li><li>Confirm whether the active host is <code>login.gunzodus.net:7171</code> and which client unlocks current features.</li><li>Create or recover accounts only through the official account pages.</li><li>Read current rules for bots, no-bot dungeons, multiclienting, PvP, trading, auctions, and payments.</li><li>Do not use reposted clients or disable security software to force an outdated build.</li></ol></section>

          <section id="history"><SectionHeading>Launch history</SectionHeading><p>The community archive records a Gunzodus launch thread by <strong>ellvo</strong> dated 10 March 2019, with 873 replies and 339,000 views. Its source context describes a European real-map project, custom content, quests, tasks, raids, Warzones, and an Android client.</p><p>A later official announcement calls Gunzodus a 15.00 Retro-PvP real-map server and says it had operated for years without reset. The official Wiki also references Summer 2024, Winter 2023, Summer 2023, and Winter 2022 updates. These milestones show a long public history, but do not prove uninterrupted service or identical rules across every client era.</p><div className="grid gap-4 md:grid-cols-3"><FactCard label="2019 archive" text="Launch discussion and historical host record by ellvo." /><FactCard label="Long-term identity" text="Official positioning emphasizes sustained progression and no-reset history." /><FactCard label="Ongoing updates" text="The official Wiki indexes multiple seasonal update periods." /></div></section>

          <section id="fit"><SectionHeading>Who Gunzodus suits</SectionHeading><p>Gunzodus is likely a strong fit for players who want a <strong>real-map Retro-PvP server</strong> with a long-term pace, a visible official Wiki, custom items, world bosses, guild competition, and alternatives to ordinary hunting. It may be less suitable for players seeking a strictly vanilla client, a fully documented single rate table, or a quiet Optional PvP environment.</p><p>Compare the official rules and current client against <a href="/servers/demolidores">Demolidores</a>, <a href="/servers/cyntara">Cyntara</a>, and <a href="/servers/rubinot">RubinOT</a> before choosing a world. Our <a href="/knowledge">OpenTibiaServers knowledge base</a> explains general terms, while Gunzodus’s own Wiki controls the live details.</p></section>

          <section id="faq"><SectionHeading>Gunzodus FAQ</SectionHeading><div className="grid gap-4"><FactCard label="What is Gunzodus?" text="Gunzodus is a real-map Open Tibia server with custom systems, active Retro-PvP, guild and castle wars, dungeons, bosses, and official Wiki documentation." /><FactCard label="What client does Gunzodus use?" text="Official pages reference Gunzodus 10, Gunzodus 12, and a 15.00-era Retro-PvP experience. Check the current Download Client page because client labels vary by source and feature." /><FactCard label="Is Gunzodus high rate?" text="The official Server Information description calls it Long-term Mid-Rate. Complete numerical rates were not reliably exposed in the reviewed extract, so verify them before starting." /><FactCard label="Does Gunzodus have no-bot dungeons?" text="Yes. The official Wiki documents no-bot dungeons with special monsters and bonuses; entry requirements and reward details belong to the current dungeon guide." /><FactCard label="How can I play safely?" text="Use only the official Gunzodus website, download page, account flow, and rules. Treat directory counts and older launch records as dated context." /></div></section>

          <section id="sources"><SectionHeading>Sources &amp; verification</SectionHeading><p>This profile prioritizes the official Gunzodus Wiki and Server Information pages for current systems, while the community archive supplies launch context. The directory snapshot is retained as a separate activity signal. Conflicting host, country, client, and rate records are intentionally not merged.</p><div className="grid gap-3 md:grid-cols-2">{links.slice(0, 12).map(([label, href]) => <SourceLink key={href} href={href} label={label} />)}</div><div className="cyntara-wiki__callout"><strong>Evidence standard</strong><p>Verify any current claim through an operator-controlled page, dated announcement, or current in-game evidence. The official site’s access and client generations can change, so refresh this reference before publishing a connection guide.</p></div></section>

          <section id="links"><SectionHeading>External links</SectionHeading><ul>{links.map(([label, href]) => <li key={href}><ExternalLink href={href}>{label}</ExternalLink></li>)}</ul></section>
        </article>
        <aside className="cyntara-wiki__sidebar"><div className="cyntara-wiki__infobox"><div className="cyntara-wiki__infobox-header">Gunzodus</div><ServerLogo server={{ name: 'Gunzodus', slug: 'gunzodus', host: 'login.gunzodus.net' }} size="profile" /><table><tbody><tr><th>Website</th><td><a href="https://gunzodus.gunzo.eu/" target="_blank" rel="nofollow noopener noreferrer">gunzodus.gunzo.eu</a></td></tr><tr><th>Current-style host</th><td><code>login.gunzodus.net:7171</code></td></tr><tr><th>Historical host</th><td><code>gunzodus.net:7171</code></td></tr><tr><th>Server type</th><td>Real map · Retro-PvP</td></tr><tr><th>Region signals</th><td>EU / Poland / historical France</td></tr><tr><th>Rate label</th><td>Long-term Mid-Rate</td></tr><tr><th>Clients</th><td>10 / 12 / 15.00-era references</td></tr><tr><th>Population</th><td>551 official capture · 186 directory snapshot</td></tr><tr><th>Custom content</th><td>Dungeons · bosses · wars · items</td></tr><tr><th>Profile status</th><td>Source-backed; snapshots differ</td></tr></tbody></table></div><div className="cyntara-wiki__callout"><strong>Before downloading</strong><p>Confirm the current host, supported client, rules, and official account path. Older launch records and newer server bars describe different snapshots.</p><a href="https://gunzodus.gunzo.eu/custom/wiki/download_client" target="_blank" rel="nofollow noopener noreferrer">Open official downloads</a></div><div className="cyntara-wiki__recommended"><h3>Explore the directory</h3><p>Compare Gunzodus with other Open Tibia worlds by version, PvP, region, rates, and activity.</p><a className="cyntara-wiki__button" href="/?search=Gunzodus">Browse similar servers</a></div></aside>
      </div>
    </main>
  );
}

function SectionHeading({ children }) { return <div className="cyntara-wiki__section-heading"><h2>{children}</h2></div>; }
function FactCard({ label, text }) { return <div className="rounded border border-black bg-white p-4"><h3 className="text-base font-bold text-black">{label}</h3><p className="mt-2 text-sm leading-7 text-black">{text}</p></div>; }
function DataTable({ headers, rows }) { return <div className="cyntara-wiki__table-wrap"><table className="cyntara-wiki__table"><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row[0]}>{row.map((cell, index) => index === 0 ? <th key={cell}>{cell}</th> : <td key={cell}>{index === 1 ? <strong>{cell}</strong> : cell}</td>)}</tr>)}</tbody></table></div>; }
function ExternalLink({ href, children }) { const external = href.startsWith('http'); return <a href={href} target={external ? '_blank' : undefined} rel={external ? 'nofollow noopener noreferrer' : undefined}>{children}</a>; }
function SourceLink({ href, label }) { return <a href={href} target="_blank" rel="nofollow noopener noreferrer" className="rounded border border-black bg-white p-4 font-bold hover:no-underline">{label}</a>; }
