import ServerLogo from '@/app/components/ServerLogo';
import DirectoryRecommendation from '@/app/components/DirectoryRecommendation';
import { getServerResearchProfile } from '@/lib/server-research-profiles';

const records = {
  iglaots: { name: 'Iglaots', host: 'play.iglaots.net:7171', type: 'Retro Open PvP', client: '15.2', exp: '3×', location: 'Poland', peak: '911', uptime: '88.84%', rating: '3.1', reviews: '1' },
  oxygenot: { name: 'OxygenOT', host: 'login.oxygenot.live:7171', type: 'PvP-Enforced', client: 'n/a', exp: '50×', location: 'Sweden', peak: '878', uptime: '99.14%', rating: '4.3', reviews: '6' },
  rexia: { name: 'Rexia', host: 'rexia.pl:7171', type: 'FUN', client: '8.6', exp: '9999×', location: 'Poland', peak: '779', uptime: '99.94%', rating: '4.0', reviews: '5' },
  calmera: { name: 'Calmera', host: 'servers.calmera.com.br:7171', type: 'Non-PvP', client: '15.0', exp: '400×', location: 'Brazil', peak: '766', uptime: '98.98%', rating: '3.7', reviews: '4' },
  paulistinhaot: { name: 'PaulistinhaOT', host: 'deletera.paulistinhaot.com:7171', type: 'PvP', client: '15.2', exp: '90×', location: 'Brazil', peak: '742', uptime: '99.42%', rating: '3.2', reviews: '2' },
  sandots: { name: 'SandOTS', host: 'sandots.eu:7171', type: 'PvP', client: '8.6', exp: '500×', location: 'Poland', peak: '735', uptime: '99.78%', rating: '3.0', reviews: '1' },
  nostalrius: { name: 'Nostalrius', host: 'on.nostalrius.com.br:7171', type: 'PvP', client: '7.4', exp: '15×', location: 'Brazil', peak: '715', uptime: '98.87%', rating: '4.2', reviews: '6' },
  taleon: { name: 'Taleon', host: 'sanpvp.taleon.online:7171', type: 'Non-PvP', client: '15.0', exp: '25×', location: 'Brazil', peak: '663', uptime: '94.37%', rating: '3.2', reviews: '2' },
};

const taleonWorlds = [
  ['Aura Lite', 'Optional PvP', '80× EXP, 3× loot, unlocked imbuements, and a shortcut-oriented onboarding model.', 'aurapvp.taleon.online:7171'],
  ['San', 'Optional PvP', '25× EXP with a more access-driven progression path.', 'sanpvp.taleon.online:7171'],
];

export default function ServerDirectoryWikiPage({ slug }) {
  const record = records[slug];
  const profile = getServerResearchProfile(slug);
  if (!record || !profile) return null;
  const title = slug === 'taleon' ? 'Taleon Online' : record.name;
  return (
    <main className="cyntara-wiki min-h-screen" data-server-slug={slug}>
      <header className="cyntara-wiki__header"><h1>{title}</h1><small>From OpenTibiaServers Wiki, the primary Open Tibia server directory</small></header>
      <div className="cyntara-wiki__grid">
        <article className="cyntara-wiki__content">
          <div className="flex flex-col gap-6 md:flex-row md:items-start"><div className="min-w-0 flex-1"><p><strong><em><u>{record.name}</u></em></strong> is a <strong>{record.type} Open Tibia server</strong> listed for players researching its current host, client, rates, systems, and community profile. This Wiki entry combines the directory snapshot with the server’s available official or source-backed research so readers can separate documented features from time-sensitive activity.</p><p>Use this page as a research guide for <em>{record.name} rates</em>, client access, rules, and progression. Always confirm the selected world and official download path before connecting.</p></div><div className="w-full shrink-0 md:w-64"><ServerLogo server={{ name: record.name, slug, host: record.host.split(':')[0] }} size="profile" /></div></div>
          <nav className="cyntara-wiki__toc" aria-label="Table of Contents"><h2>Contents</h2><ol>{[['overview','Overview & identity'],['facts','Reference facts'],['systems','Systems & progression'],['community','PvP, community & how to start'],['sources','Sources & verification'],['external-links','External links']].map(([id,label]) => <li key={id}><a href={`#${id}`}>{label}</a></li>)}</ol></nav>
          <section id="overview"><SectionHeading>Overview &amp; identity</SectionHeading><p>{profile.summary}</p><p>{profile.features[0]} {profile.features[1]}</p><div className="cyntara-wiki__callout"><strong>Evidence scope</strong><p>Directory values such as players, uptime, ratings, and reviews are snapshots. Feature descriptions come from the listed research profile and official sources; schedules, prices, rules, and availability may change.</p></div></section>
          <section id="facts"><SectionHeading>Reference facts</SectionHeading><Table headers={['Field','Recorded value','Context']} rows={[["Connection",record.host,'Verify the current endpoint on the official site.'],['Server type',record.type,'Directory classification.'],['Client',record.client,'Confirm the active client or launcher before downloading.'],['Experience',record.exp,'Headline directory rate; staged systems may differ.'],['Location',record.location,'Directory region signal.'],['Peak players',record.peak,'Historical directory snapshot.'],['Uptime',record.uptime,'Historical directory snapshot, not an SLA.'],['Rating',`${record.rating} / 5 (${record.reviews} reviews)`,'Community signal, not a guarantee of current quality.']]} /></section>
          <section id="systems"><SectionHeading>Systems &amp; progression</SectionHeading><p>The published identity for {record.name} includes the following searchable features and progression hooks:</p><ul>{profile.features.map((feature) => <li key={feature}><strong>{feature.split(' ')[0]}</strong>{feature.slice(feature.split(' ')[0].length)}</li>)}</ul>{slug === 'taleon' && <Table headers={['World','PvP','Progression profile','Endpoint']} rows={taleonWorlds} />}{slug === 'iglaots' && <p>The IglaOTS research profile names a reworked Task Board, Forge, Enchanting, hourly Igla Tokens, Loyalty rewards, Global Charms, personal boss loot, Nemesis bosses, and reworked monsters. Its Season, Offseason, and Lowrate variants should be checked against the live wiki.</p>}{slug === 'oxygenot' && <p>OxygenOT’s official wiki research describes a custom world and client with crafting, fishing, daily chests and tasks, attribute points, item upgrading, dynamic spawns, custom dungeons, bosses, Battlefield, and Capture the Flag.</p>}{slug === 'rexia' && <p>Rexia’s documented identity centers on an 8.60 4FUN RPG High-EXP EVO experience with Reborn, markets, character auctions, house building, and the Addict System.</p>}{slug === 'sandots' && <p>SandOTS research names Reborn, task points, dungeons, daily bosses, hunting arena, automatic loot, addon fountains, head-hunter, war, and customizable house floors. Its FAQ should be checked for the current PvP unlock and timers.</p>}{slug === 'nostalrius' && <p>Nostalrius research describes a 7.4 Retro Open-PvP ecosystem with multiworld hosting, staged rates, stamina-linked experience and loot, auto-raids, daily bosses, forge tiers, party-task bonuses, and Desert Quest Solo.</p>}{slug === 'paulistinhaot' && <p>PaulistinhaOT is documented as a multiworld network with distinct PvP identities, Roulette, Mystery Bag, Weapon Proficiency, scalable bosses, Echo Raids, Discovery, weekly tasks, and Targuna.</p>}{slug === 'calmera' && <p>Calmera research describes Anthera and Emporium worlds, optional PvP, global and VIP maps, instances on Anthera, and an open player economy on Emporium. Confirm world selection and current client details officially.</p>}</section>
          <section id="community"><SectionHeading>PvP, community &amp; how to start</SectionHeading><p>Before joining {record.name}, compare the current rules, world status, client requirements, and community channels. PvP labels and historical activity do not fully describe frag rules, death penalties, event restrictions, transfers, or enforcement.</p><ol><li>Open the official source links below and verify the current world or server information.</li><li>Use the official download or launcher path; avoid copied mirrors and credential requests.</li><li>Read rules and account terms before trading, bidding, or joining competitive activities.</li><li>Compare this profile with the live <a href="/">OpenTibiaServers directory</a> shortly before playing.</li></ol></section>
          <section id="sources"><SectionHeading>Sources &amp; verification</SectionHeading><p>Primary sources are listed in the server research profile. The directory snapshot contributes host, activity, uptime, and rating context. Treat historical excerpts and community discussions as dated evidence rather than permanent server rules.</p><div className="grid gap-3 md:grid-cols-2">{profile.sources.map((source) => <SourceLink key={source.href} href={source.href} label={source.label} />)}</div></section>
          <DirectoryRecommendation />
          <section id="external-links"><SectionHeading>External links</SectionHeading><ul>{profile.sources.map((source) => <li key={source.href}><ExternalLink href={source.href}>{source.label}</ExternalLink></li>)}<li><a href="/">OpenTibiaServers directory</a></li></ul></section>
        </article>
        <aside className="cyntara-wiki__sidebar"><div className="cyntara-wiki__infobox"><div className="cyntara-wiki__infobox-header">{record.name}</div><ServerLogo server={{ name: record.name, slug, host: record.host.split(':')[0] }} size="profile" /><Table headers={['Field','Value']} rows={[["Host",record.host],["Type",record.type],["Client",record.client],["EXP",record.exp],["Location",record.location],["Peak",record.peak],["Uptime",record.uptime],["Rating",`${record.rating} (${record.reviews})`]]} /></div><div className="cyntara-wiki__callout"><strong>Before downloading</strong><p>Verify the official client, world, rules, and account path.</p></div><div className="cyntara-wiki__recommended"><h3>Explore the directory</h3><p>Compare live Open Tibia listings by version, PvP type, location, activity, and community signals.</p><a className="cyntara-wiki__button" href="/">Browse server listings</a></div></aside>
      </div>
    </main>
  );
}

function SectionHeading({ children }) { return <div className="cyntara-wiki__section-heading"><h2>{children}</h2></div>; }
function Table({ headers, rows }) { return <div className="cyntara-wiki__table-wrap"><table className="cyntara-wiki__table"><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row[0]}>{row.map((value, index) => index === 0 ? <th key={value}>{value}</th> : <td key={`${row[0]}-${index}`}>{index === 1 ? <strong>{value}</strong> : value}</td>)}</tr>)}</tbody></table></div>; }
function ExternalLink({ href, children }) { const external = href.startsWith('http'); return <a href={href} target={external ? '_blank' : undefined} rel={external ? 'nofollow noopener noreferrer' : undefined}>{children}</a>; }
function SourceLink({ href, label }) { return <ExternalLink href={href}><span className="block rounded border border-black bg-white p-4 font-bold hover:no-underline">{label}</span></ExternalLink>; }
