export const dynamic = 'force-dynamic';

import ItemsClient from './ItemsClient';

const itemData = {
  equipment_slots: {
    helmet: {
      label: "Helmets",
      description: "Protective headgear providing defense and armor bonuses",
      items: [
        { id: "40952", name: "Cosmic Helmet", tier: "Rare", weight: 1800, armor: 10, stats: { physical_protection: 2 } },
        { id: "40953", name: "Kraken Helmet", tier: "Uncommon", weight: 1000, armor: 8, stats: { fire_protection: 2, distance_fighting: 2, sword_fighting: 2, magic_level: 2, critical_hit_chance: 1 } },
        { id: "2493", name: "Demon Helmet", tier: "Uncommon", weight: 2950, armor: 10, stats: { distance_fighting: 1, sword_fighting: 1, magic_level: 1 } },
        { id: "7901", name: "Magic Helmet", tier: "Uncommon", weight: 100, armor: 10, stats: { hp_regen: 50, mp_regen: 50, holy_protection: 1 } },
        { id: "6531", name: "Santa Hat", tier: "Uncommon", weight: 750, armor: 9, stats: { fire_protection: 3, critical_hit_chance: 2 } },
        { id: "40979", name: "Gladiator Helmet", tier: "Uncommon", weight: 750, armor: 11, stats: { max_health: 2, max_mana: 2 } },
        { id: "2471", name: "Golden Helmet", tier: "Rare", weight: 3200, armor: 15, stats: { distance_fighting: 1, sword_fighting: 1, magic_level: 1, physical_protection: 3, speed: 20, attack_speed: 3 } },
        { id: "2506", name: "Dragon Scale Helmet", tier: "Rare", weight: 6000, armor: 16, stats: { distance_fighting: 2, sword_fighting: 2, magic_level: 2 } },
        { id: "40980", name: "Devilish Helmet", tier: "Rare", weight: 6000, armor: 18, stats: { distance_fighting: 2, sword_fighting: 2, magic_level: 2, fire_protection: 3, mana_drain_protection: 3, critical_hit_chance: 3 } },
        { id: "2502", name: "Blessed Helmet", tier: "Rare", weight: 4200, armor: 20, stats: { holy_protection: 4, life_drain_protection: 5, fire_protection: -5, attack_speed: 3 } },
        { id: "40888", name: "Gryphon Mask", tier: "Rare", weight: 1200, armor: 28, stats: { ice_protection: 8, death_protection: 5, energy_protection: -6, speed: 40 } },
        { id: "40889", name: "Conqueror Helmet", tier: "Rare", weight: 3200, armor: 30, stats: { physical_protection: 5, mana_drain_protection: 8, earth_protection: -5, distance_fighting: 5, sword_fighting: 5, magic_level: 5, attack_speed: 5 } },
        { id: "40860", name: "Ominous Helmet", tier: "Rare", weight: 4300, armor: 22, stats: { extra_weapon_attack: 6, max_health: 5, max_mana: 5, speed: 20 } },
        { id: "46116", name: "Serenity Helmet", tier: "Rare", weight: 4300, armor: 35, stats: { death_protection: 4, energy_protection: 4, fire_protection: 4, earth_protection: 4, ice_protection: 4, max_health: 18, max_mana: 18, dodge: 5, critical_hit_chance: 5 } },
        { id: "41427", name: "Titan Wrath Helmet", tier: "Legendary", weight: 4300, armor: 35, stats: { death_protection: 4, energy_protection: 4, fire_protection: 4, earth_protection: 4, ice_protection: 4, max_health: 18, max_mana: 18, dodge: 5, critical_hit_chance: 5 } },
        { id: "2663", name: "Mystic Turban", tier: "Uncommon", weight: 100, armor: 10, stats: { hp_regen: 50, mp_regen: 50, holy_protection: 1 } },
        { id: "13756", name: "Mage's Cap", tier: "Uncommon", weight: 750, armor: 11, stats: { max_health: 2, max_mana: 2 } },
        { id: "25413", name: "Shroud of Despair", tier: "Rare", weight: 6000, armor: 18, stats: { magic_level: 2, fire_protection: 3 } },
        { id: "25410", name: "Visage of the End Days", tier: "Rare", weight: 3800, armor: 18, stats: { distance_fighting: 2, sword_fighting: 2, fire_protection: 3 } },
        { id: "5903", name: "Ferumbras Hat", tier: "Rare", weight: 850, armor: 1, description: "It is the proof that Ferumbras has fallen" }
      ]
    },
    armor: {
      label: "Armors",
      description: "Body armor providing core defense and damage reduction",
      items: [
        { id: "40954", name: "Cosmic Armor", tier: "Rare", weight: 2250, armor: 100, stats: {} },
        { id: "2494", name: "Demon Armor", tier: "Uncommon", weight: 8000, armor: 80, stats: { attack_speed: 2 } },
        { id: "7898", name: "Magic Armor", tier: "Uncommon", weight: 2250, armor: 100, stats: { ice_protection: 4, death_protection: 3, max_mana: 2 } },
        { id: "40890", name: "Royal Scale Robe", tier: "Rare", weight: 2250, armor: 150, stats: { death_protection: 3, mana_drain_protection: 2, attack_speed: 3 } },
        { id: "40956", name: "Ornate Chestplate", tier: "Rare", weight: 2250, armor: 170, stats: { physical_protection: 4 } },
        { id: "40957", name: "Furious Frock", tier: "Rare", weight: 2250, armor: 180, stats: { shielding: 3, fire_protection: 5, death_protection: 5, holy_protection: 5, mana_drain_protection: 2, hp_regen: 300, mp_regen: 300, speed: 30 } },
        { id: "40892", name: "Crusader Armor", tier: "Rare", weight: 14000, armor: 250, stats: { mana_drain_protection: 5, earth_protection: 7, fire_protection: 7, ice_protection: -12, distance_fighting: 5, sword_fighting: 5, magic_level: 5, attack_speed: 4 } },
        { id: "40894", name: "Azurite Robe", tier: "Rare", weight: 10000, armor: 230, stats: { ice_protection: 6, energy_protection: 7, death_protection: -6, hp_regen: 800, mp_regen: 1200, max_mana: 5 } },
        { id: "40897", name: "Skull Robe", tier: "Rare", weight: 11000, armor: 350, stats: { max_health: 10, max_mana: 10, hp_regen: 1000, mp_regen: 1400 } },
        { id: "40958", name: "Fireheart Cuirass", tier: "Rare", weight: 11000, armor: 300, stats: { distance_fighting: 10, sword_fighting: 10, magic_level: 10 } },
        { id: "40960", name: "Fireheart Platemail", tier: "Rare", weight: 11000, armor: 300, stats: { critical_hit_chance: 10 } },
        { id: "40961", name: "Firesoul Tabard", tier: "Rare", weight: 11000, armor: 300, stats: { attack_speed: 10 } },
        { id: "40962", name: "Firemind Raiment", tier: "Rare", weight: 11000, armor: 300, stats: { max_health: 10, max_mana: 10 } },
        { id: "8821", name: "Witchhunter's Coat", tier: "Uncommon", weight: 2250, armor: 100, stats: { ice_protection: 2, death_protection: 2, max_mana: 2 } },
        { id: "2503", name: "Dwarven Armor", tier: "Uncommon", weight: 2250, armor: 140, stats: { mana_drain_protection: 2, physical_protection: 2, speed: 10, max_health: 2, shielding: 3 } },
        { id: "8865", name: "Dark Lord's Cape", tier: "Rare", weight: 2250, armor: 150, stats: { death_protection: 3, mana_drain_protection: 2, attack_speed: 3 } },
        { id: "37463", name: "Ghost Chestplate", tier: "Uncommon", weight: 2250, armor: 170, stats: { physical_protection: 4, mana_leech: 0.06, life_leech: 0.06 } },
        { id: "15407", name: "Depth Lorica", tier: "Rare", weight: 2250, armor: 180, stats: { shielding: 3, fire_protection: 3, death_protection: 3, holy_protection: 3, earth_protection: 3, mana_drain_protection: 2, hp_regen: 100, mp_regen: 200 } },
        { id: "2656", name: "Blue Robe", tier: "Uncommon", weight: 2200, armor: 1 },
        { id: "2476", name: "Knight Armor", tier: "Uncommon", weight: 12000, armor: 1 },
        { id: "3968", name: "Leopard Armor", tier: "Uncommon", weight: 9500, armor: 1 },
        { id: "2500", name: "Amazon Armor", tier: "Uncommon", weight: 4500, armor: 1 },
        { id: "8888", name: "Master Archer's Armor", tier: "Uncommon", weight: 6900, armor: 1 },
        { id: "2472", name: "Magic Plate Armor", tier: "Uncommon", weight: 8500, armor: 1 },
        { id: "8885", name: "Divine Plate", tier: "Uncommon", weight: 7500, armor: 1 },
        { id: "8884", name: "Oceanborn Leviathan Armor", tier: "Uncommon", weight: 10000, armor: 1 },
        { id: "8880", name: "Swamplair Armor", tier: "Uncommon", weight: 8450, armor: 1 },
        { id: "8889", name: "Skullcracker Armor", tier: "Uncommon", weight: 11000, armor: 1 },
        { id: "8887", name: "Frozen Plate", tier: "Uncommon", weight: 7500, armor: 1 },
        { id: "8891", name: "Paladin Armor", tier: "Uncommon", weight: 6500, armor: 1 },
        { id: "11356", name: "Zaoan Robe", tier: "Uncommon", weight: 2450, armor: 1 },
        { id: "2466", name: "Golden Armor", tier: "Uncommon", weight: 8000, armor: 1 },
        { id: "2492", name: "Dragon Scale Mail", tier: "Uncommon", weight: 11400, armor: 1 },
        { id: "12607", name: "Elite Draken Mail", tier: "Uncommon", weight: 12000, armor: 1 },
        { id: "11301", name: "Zaoan Armor", tier: "Uncommon", weight: 9550, armor: 1 },
        { id: "21725", name: "Furious Frock", tier: "Uncommon", weight: 2250, armor: 80 }
      ]
    },
    shield: {
      label: "Shields",
      description: "Defensive equipment providing protection and defense bonuses",
      items: [
        { id: "7460", name: "Norse Shield", tier: "Rare", weight: 4100, defense: 120, stats: { shielding: 1, physical_protection: 2, fire_protection: 2 } },
        { id: "3973", name: "Tusk Shield", tier: "Rare", weight: 6900, defense: 130, stats: { shielding: 1, holy_protection: 2, death_protection: 2 } },
        { id: "40922", name: "Lion Shield", tier: "Rare", weight: 8400, defense: 180, stats: { shielding: 2, fire_protection: 4, death_protection: 3 } },
        { id: "40923", name: "Ornate Shield", tier: "Rare", weight: 8400, defense: 230, stats: { shielding: 2, physical_protection: 3, ice_protection: 4, fire_protection: -5 } },
        { id: "40876", name: "Shield of Corruption", tier: "Rare", weight: 4900, defense: 300, stats: { shielding: 3, physical_protection: 4, fire_protection: 6 } },
        { id: "2539", name: "Phoenix Shield", tier: "Rare", weight: 3500, defense: 350, stats: { shielding: 3, holy_protection: 4, death_protection: 4 } },
        { id: "2542", name: "Tempest Shield", tier: "Rare", weight: 5100, defense: 400, stats: { shielding: 3, energy_protection: 6, ice_protection: 6, earth_protection: 6 } },
        { id: "40971", name: "Shield of Achilles", tier: "Rare", weight: 6800, defense: 1500, stats: { shielding: 8, physical_protection: 8, fire_protection: 10, reflect_chance: 10, reflect_damage: 50, dodge: 3 } },
        { id: "40970", name: "Svalinn Shield", tier: "Rare", weight: 6800, defense: 1800, stats: { shielding: 8, energy_protection: 10, ice_protection: 10, earth_protection: 10, reflect_chance: 10, reflect_damage: 50, dodge: 3 } },
        { id: "2523", name: "Blessed Shield", tier: "Uncommon", weight: 8400, defense: 180, stats: { shielding: 2, holy_protection: 2, death_protection: 2 } },
        { id: "6391", name: "Nightmare Shield", tier: "Uncommon", weight: 8400, defense: 230, stats: { shielding: 2, physical_protection: 3, fire_protection: 5 } },
        { id: "6433", name: "Necromancer Shield", tier: "Rare", weight: 5100, defense: 480, stats: { shielding: 2, death_protection: 5, ice_protection: 3, extra_weapon_attack: 5 } },
        { id: "2517", name: "Shield of Honour", tier: "Rare", weight: 5400, defense: 280, stats: { shielding: 5, physical_protection: 4, fire_protection: 2 } },
        { id: "40851", name: "Titan Shield", tier: "Rare", weight: 5100, defense: 550, stats: { dodge: 2, damage_reduction: 4 } },
        { id: "12647", name: "Snake God's Wristguard", tier: "Rare", weight: 5100, defense: 450, stats: { dodge: 2, damage_increase: 4 } },
        { id: "40821", name: "Rich Shield", tier: "Legendary", weight: 8400, defense: 280, stats: { shielding: 3, extra_weapon_attack: 5 } },
        { id: "16112", name: "Rich Spellbook", tier: "Legendary", weight: 8400, defense: 300, stats: { magic_level: 3, extra_weapon_attack: 10 } },
        { id: "8902", name: "Spellbook of Mind Control", tier: "Uncommon", weight: 2450, magic_level: 2, defense: 14, weaponType: "shield" },
        { id: "2529", name: "Black Shield", tier: "Uncommon", weight: 4200, defense: 1 },
        { id: "2534", name: "Vampire Shield", tier: "Uncommon", weight: 3800, defense: 1 },
        { id: "2537", name: "Amazon Shield", tier: "Uncommon", weight: 6200, defense: 1 },
        { id: "2514", name: "Mastermind Shield", tier: "Uncommon", weight: 5700, defense: 1 },
        { id: "2536", name: "Medusa Shield", tier: "Uncommon", weight: 5800, defense: 1 },
        { id: "2516", name: "Dragon Shield", tier: "Uncommon", weight: 6000, defense: 1 },
        { id: "2520", name: "Demon Shield", tier: "Uncommon", weight: 2600, defense: 1 },
        { id: "2522", name: "Great Shield", tier: "Uncommon", weight: 8400, defense: 1 },
        { id: "8918", name: "Spellbook of Dark Mysteries", tier: "Uncommon", weight: 2850, magic_level: 4, defense: 18, weaponType: "shield" }
      ]
    },
    legs: {
      label: "Legs",
      description: "Leg protection for lower body defense and mobility",
      items: [
        { id: "40941", name: "Cosmic Legs", tier: "Rare", weight: 1900, armor: 50, stats: { hp_regen: 100, mp_regen: 100 } },
        { id: "40976", name: "Assassin Legs", tier: "Rare", weight: 1900, armor: 60, stats: { attack_speed: 3 } },
        { id: "40942", name: "Ornate Legs", tier: "Rare", weight: 1900, armor: 65, stats: { physical_protection: 1, ice_protection: 3, life_drain_protection: 3, max_health: 1, max_mana: 1 } },
        { id: "2507", name: "Elven Legs", tier: "Rare", weight: 4000, armor: 80, stats: { physical_protection: 2, life_drain_protection: 5, earth_protection: 5, critical_hit_chance: 2 } },
        { id: "40943", name: "Fabulous Legs", tier: "Rare", weight: 4200, armor: 200, stats: { physical_protection: 5, fire_protection: 8, holy_protection: 4, life_drain_protection: 8, speed: 60, critical_hit_chance: 2 } },
        { id: "40883", name: "Ethno Legs", tier: "Rare", weight: 4500, armor: 220, stats: { distance_fighting: 5, sword_fighting: 5, magic_level: 5, death_protection: 5, earth_protection: 8, speed: 80, attack_speed: 6 } },
        { id: "40977", name: "Eldritch Breeches", tier: "Rare", weight: 4500, armor: 250, stats: { attack_speed: 8, energy_protection: 8, ice_protection: 8, earth_protection: 8, distance_fighting: 4, sword_fighting: 4, magic_level: 4 } },
        { id: "40944", name: "Soulshanks", tier: "Rare", weight: 4500, armor: 250, stats: { critical_hit_chance: 3, physical_protection: 6, fire_protection: 9, distance_fighting: 6, sword_fighting: 6, magic_level: 6 } },
        { id: "40947", name: "Exotic Legs", tier: "Rare", weight: 4500, armor: 300, stats: { critical_hit_chance: 4, sword_fighting: 6, magic_level: 6, distance_fighting: 6, physical_protection: 8, fire_protection: 10 } },
        { id: "40948", name: "Soulstrider", tier: "Rare", weight: 4500, armor: 300, stats: { attack_speed: 15, sword_fighting: 6, magic_level: 6, distance_fighting: 6, energy_protection: 10, earth_protection: 10, ice_protection: 10 } },
        { id: "40852", name: "Nubien Legs", tier: "Rare", weight: 4000, armor: 180, stats: { damage_increase: 6, speed: 20 } },
        { id: "46127", name: "Forsaken Legs", tier: "Rare", weight: 4000, armor: 220, stats: { damage_increase: 10 } },
        { id: "46118", name: "Serenity Legs", tier: "Rare", weight: 4000, armor: 300, stats: { critical_hit_chance: 3, damage_increase: 15, death_protection: 6 } },
        { id: "41429", name: "Titan Wrath Legs", tier: "Legendary", weight: 4000, armor: 300, stats: { critical_hit_chance: 3, damage_increase: 15, death_protection: 6 } },
        { id: "2504", name: "Dwarven Legs", tier: "Uncommon", weight: 1900, armor: 40, stats: { holy_protection: 2, death_protection: 2, distance_fighting: 2, sword_fighting: 2, magic_level: 2 } },
        { id: "15409", name: "Depth Ocrea", tier: "Uncommon", weight: 4500, armor: 40, stats: { holy_protection: 2, death_protection: 2, magic_level: 2 } },
        { id: "7730", name: "Blue Legs", tier: "Uncommon", weight: 1900, armor: 30, stats: { energy_protection: 3, hp_regen: 100, mp_regen: 100 } },
        { id: "15490", name: "Grasshopper Legs", tier: "Uncommon", weight: 1900, armor: 60, stats: { life_leech: 0.06, attack_speed: 3 } },
        { id: "40351", name: "Ancestor Legs", tier: "Rare", weight: 4800, armor: 100, stats: { distance_fighting: 2, sword_fighting: 2, attack_speed: 4 } },
        { id: "46835", name: "Magic Legs", tier: "Rare", weight: 4800, armor: 100, stats: { magic_level: 2, attack_speed: 4 } },
        { id: "3983", name: "Bast Skirt", tier: "Uncommon", weight: 350, armor: 1 },
        { id: "2495", name: "Demon Legs", tier: "Uncommon", weight: 5400, armor: 1 },
        { id: "2469", name: "Dragon Scale Legs", tier: "Uncommon", weight: 5400, armor: 1 },
        { id: "2470", name: "Golden Legs", tier: "Uncommon", weight: 5600, armor: 1 },
        { id: "2477", name: "Knight Legs", tier: "Uncommon", weight: 7000, armor: 1 },
        { id: "7894", name: "Magma Legs", tier: "Rare", weight: 5400, armor: 1 },
        { id: "11304", name: "Zaoan Legs", tier: "Rare", weight: 6600, armor: 1 },
        { id: "7895", name: "Lightning Legs", tier: "Rare", weight: 1900, armor: 1 }
      ]
    },
    boots: {
      label: "Boots",
      description: "Footwear enhancing mobility, defense, and regeneration",
      items: [
        { id: "40884", name: "Boots of Fire", tier: "Rare", weight: 100, armor: 0, stats: { fire_protection: 30 } },
        { id: "2358", name: "Cosmic Boots", tier: "Uncommon", weight: 800, armor: 9, stats: { hp_regen: 50, mp_regen: 50, speed: 40 } },
        { id: "2641", name: "Blessed Boots", tier: "Uncommon", weight: 900, armor: 15, stats: { physical_protection: 2, death_protection_reflect: 5, death_protection_reflect_chance: 10, speed: 60 } },
        { id: "40885", name: "Eternal Boots", tier: "Rare", weight: 800, armor: 18, stats: { death_protection: 3, earth_protection: 5, holy_protection_reflect: 10, holy_protection_reflect_chance: 10, speed: 70 } },
        { id: "40886", name: "Arcane Boots", tier: "Rare", weight: 800, armor: 25, stats: { life_drain_protection: 5, mana_drain_protection: 5, physical_protection: 3, fire_protection_reflect: 10, fire_protection_reflect_chance: 10, speed: 100, critical_hit_chance: 2, attack_speed: 3 } },
        { id: "40951", name: "Austere Boots", tier: "Rare", weight: 2500, armor: 22, stats: { speed: 40, mana_leech: 0.16, reflect_chance: 10, reflect_damage: 30, hp_regen: 300, mp_regen: 300 } },
        { id: "6132", name: "Soft Boots", tier: "Uncommon", weight: 850, armor: 11, stats: { speed: 20, energy_protection: 2, fire_protection: 2, death_protection: 1, hp_regen: 80, mp_regen: 80 } },
        { id: "9932", name: "Firewalker Boots", tier: "Uncommon", weight: 750, armor: 9, stats: { speed: 20, fire_protection: 10, hp_regen: 40, mp_regen: 40 } },
        { id: "2646", name: "Golden Boots", tier: "Uncommon", weight: 850, armor: 10, stats: { speed: 20, energy_protection: 2, physical_protection: 1, hp_regen: 80, mp_regen: 80 } },
        { id: "40949", name: "Kraken Boots", tier: "Uncommon", weight: 850, armor: 13, stats: { speed: 20, hp_regen: 150, mp_regen: 150, mana_leech: 0.03, life_leech: 0.03 } },
        { id: "12646", name: "Draken Boots", tier: "Rare", weight: 2500, armor: 18, stats: { hp_regen: 300, mp_regen: 300, speed: 40 } },
        { id: "46050", name: "Bloodforge Boots", tier: "Rare", weight: 2500, armor: 24, stats: { speed: 40, hp_regen: 500, mp_regen: 800, reflect_chance: 15, reflect_damage: 50 } },
        { id: "46119", name: "Serenity Boots", tier: "Rare", weight: 2500, armor: 35, stats: { speed: 40, hp_regen: 1500, mp_regen: 1500, life_leech: 0.33, mana_leech: 0.33, reflect_chance: 25, reflect_damage: 50 } },
        { id: "41430", name: "Titan Wrath Boots", tier: "Legendary", weight: 2500, armor: 35, stats: { speed: 40, hp_regen: 1500, mp_regen: 1500, life_leech: 0.33, mana_leech: 0.33, reflect_chance: 25, reflect_damage: 50 } },
        { id: "5462", name: "Pirate Boots", tier: "Uncommon", weight: 600 },
        { id: "11118", name: "Dragon Scale Boots", tier: "Uncommon", weight: 1850 },
        { id: "11240", name: "Guardian Boots", tier: "Uncommon", weight: 2250 },
        { id: "2645", name: "Steel Boots", tier: "Uncommon", weight: 2900 },
        { id: "11117", name: "Crystal Boots", tier: "Uncommon", weight: 1850 },
        { id: "2195", name: "Boots of Haste", tier: "Uncommon", weight: 70 },
        { id: "2644", name: "Bunnyslippers", tier: "Uncommon", weight: 600 },
        { id: "46128", name: "Forsaken Boots", tier: "Rare", weight: 2500, armor: 26 }
      ]
    },
    amulet: {
      label: "Amulets",
      description: "Magical pendants worn around the neck for power and bonuses",
      items: [
        { id: "2173", name: "Amulet of Loss", tier: "Uncommon", weight: 420, stats: { prevent_drop: 1, charges: 1 } },
        { id: "2197", name: "Stone Skin Amulet", tier: "Uncommon", weight: 700, stats: { physical_protection: 25, charges: 5 } },
        { id: "2198", name: "Elven Amulet", tier: "Uncommon", weight: 270, stats: { physical_protection: 10, fire_protection: 10, ice_protection: 10, earth_protection: 10, death_protection: 10, holy_protection: 10, energy_protection: 10, charges: 15 } },
        { id: "40877", name: "Exotic Amulet", tier: "Rare", weight: 1200, stats: { hp_regen: 1000, mp_regen: 1000, prevent_drop: 1 } },
        { id: "40878", name: "Glowing Amulet", tier: "Rare", weight: 1500, stats: { distance_fighting: 10, sword_fighting: 10, magic_level: 10, prevent_drop: 1 } },
        { id: "40925", name: "Collar of Blue Plasma", tier: "Rare", weight: 1200, stats: { hp_regen: 1200, mp_regen: 1200, attack_speed: 7, prevent_drop: 1 } },
        { id: "40926", name: "Collar of Red Plasma", tier: "Rare", weight: 1500, stats: { distance_fighting: 12, sword_fighting: 12, magic_level: 12, prevent_drop: 1, critical_hit_chance: 4 } },
        { id: "2218", name: "Mystic Ember Amulet", tier: "Rare", weight: 1000, stats: { hp_regen: 125, mp_regen: 125, prevent_drop: 1, extra_weapon_attack: 5 } },
        { id: "7888", name: "Glacier Amulet", tier: "Rare", weight: 500, stats: { hp_regen: 500, mp_regen: 500 } },
        { id: "2138", name: "Sapphire Amulet", tier: "Rare", weight: 1000, stats: { attack_speed: 5, max_health: 3, max_mana: 3 } },
        { id: "23541", name: "Gearwheel Chain", tier: "Rare", weight: 1000, stats: { critical_hit_chance: 4, hp_regen: 150, mp_regen: 150 } },
        { id: "2171", name: "Crown Amulet", tier: "Uncommon", weight: 80, stats: { hp_regen: 5, mp_regen: 5 } },
        { id: "2131", name: "Yalahari Amulet", tier: "Rare", weight: 610, stats: { hp_regen: 80, mp_regen: 80, extra_weapon_attack: 3 } },
        { id: "40857", name: "Rich Amulet", tier: "Legendary", weight: 610, stats: { hp_regen: 150, mp_regen: 150 } },
        { id: "2196", name: "Soul Amulet", tier: "Legendary", weight: 1000, stats: { hp_regen: 320, mp_regen: 320, max_health: 5, max_mana: 5 } },
        { id: "8266", name: "Dwarven Amulet", tier: "Uncommon", weight: 80, stats: { hp_regen: 15, mp_regen: 15 } },
        { id: "41477", name: "Amulet of Red Skull", tier: "Legendary", weight: 1200, stats: { skill_loss_reduction: 18, health_regeneration: 380, mana_regeneration: 380, max_health: 7, max_mana: 7, damage_reduction: 4, extra_weapon_attack: 10 } },
        { id: "41478", name: "Violet Eye Amulet", tier: "Legendary", weight: 1200, stats: { health_regeneration: 420, mana_regeneration: 420, max_health: 9, max_mana: 9, critical_hit_chance: 4, magic_level: 5, extra_weapon_attack: 14 } }
      ]
    },
    ring: {
      label: "Rings",
      description: "Enchanted rings providing various combat and magical bonuses",
      items: [
        { id: "2164", name: "Might Ring", tier: "Uncommon", weight: 100, stats: { physical_protection: 25, charges: 20 } },
        { id: "2168", name: "Life Ring", tier: "Uncommon", weight: 80, stats: { transform_equip_to: "2205", duration: 3600, hp_regen: 50, mp_regen: 100 } },
        { id: "2205", name: "Life Ring", tier: "Uncommon", weight: 80, stats: { hp_regen: 50, mp_regen: 100 } },
        { id: "2213", name: "Dwarven Ring", tier: "Uncommon", weight: 110, stats: { suppress_drunk: 1, duration: 3600 } },
        { id: "2215", name: "Dwarven Ring", tier: "Uncommon", weight: 110 },
        { id: "2214", name: "Ring of Healing", tier: "Uncommon", weight: 80, stats: { hp_regen: 100, mp_regen: 200, duration: 3600 } },
        { id: "2216", name: "Ring of Healing", tier: "Uncommon", weight: 80 },
        { id: "2208", name: "Axe Ring", tier: "Uncommon", weight: 90, stats: { sword_fighting: 4, duration: 1800 } },
        { id: "2211", name: "Axe Ring", tier: "Uncommon", weight: 90 },
        { id: "2209", name: "Wand Ring", tier: "Uncommon", weight: 90, stats: { magic_level: 10, duration: 3600 } },
        { id: "2212", name: "Wand Ring", tier: "Uncommon", weight: 90 },
        { id: "2207", name: "Melee Ring", tier: "Uncommon", weight: 90, stats: { sword_fighting: 10, duration: 3600 } },
        { id: "2210", name: "Melee Ring", tier: "Uncommon", weight: 90 },
        { id: "2166", name: "Distance Ring", tier: "Uncommon", weight: 80, stats: { distance_fighting: 10, duration: 3600 } },
        { id: "2203", name: "Distance Ring", tier: "Uncommon", weight: 80 },
        { id: "2169", name: "Time Ring", tier: "Uncommon", weight: 90, stats: { speed: 100, duration: 3600 } },
        { id: "2206", name: "Time Ring", tier: "Uncommon", weight: 90 },
        { id: "2165", name: "Stealth Ring", tier: "Uncommon", weight: 100, stats: { invisible: 1, duration: 3600 } },
        { id: "2202", name: "Stealth Ring", tier: "Uncommon", weight: 100 },
        { id: "2167", name: "Energy Ring", tier: "Uncommon", weight: 80, stats: { mana_shield: 1, duration: 3600 } },
        { id: "2204", name: "Energy Ring", tier: "Uncommon", weight: 80 },
        { id: "40880", name: "Ring of Physical", tier: "Uncommon", weight: 100, stats: { physical_protection: 10, charges: 20 } },
        { id: "40928", name: "Prismatic Ring", tier: "Rare", weight: 170, stats: { life_drain_protection: 5, physical_protection: 2, hp_regen: 50, mp_regen: 50, critical_hit_chance: 2 } },
        { id: "40929", name: "Strike Ring", tier: "Rare", weight: 170, stats: { distance_fighting: 5, sword_fighting: 5, magic_level: 5, critical_hit_chance: 5, attack_speed: 10, hp_regen: 300, mp_regen: 300 } },
        { id: "40931", name: "Plasma Ring", tier: "Rare", weight: 170, stats: { max_health: 8, max_mana: 8, hp_regen: 700, mp_regen: 700, energy_protection: 10, earth_protection: 10, death_protection: 10, ice_protection: 10, fire_protection: 10 } },
        { id: "7967", name: "Royal Ring", tier: "Uncommon", weight: 170, stats: { hp_regen: 85, mp_regen: 85, physical_protection: 2 } },
        { id: "7697", name: "Mystic Ember Ring", tier: "Rare", weight: 80, stats: { distance_fighting: 2, sword_fighting: 2, extra_weapon_attack: 5, speed: 20 } },
        { id: "7708", name: "Mystic Ember Ring", tier: "Rare", weight: 80, stats: { magic_level: 2, extra_weapon_attack: 5, speed: 20 } },
        { id: "40932", name: "Vampire's Signet Ring", tier: "Rare", weight: 170, stats: { hp_regen: 250, mp_regen: 250, damage_reduction: 4 } },
        { id: "40933", name: "Sweetheart Ring", tier: "Rare", weight: 170, stats: { damage_increase: 4, hp_regen: 150, mp_regen: 150 } },
        { id: "13826", name: "Star Ring", tier: "Rare", weight: 170, stats: { attack_speed: 10, hp_regen: 500, mp_regen: 500, extra_weapon_attack: 10, ice_protection: 6 } },
        { id: "36451", name: "Soul Ring", tier: "Legendary", weight: 80, stats: { dodge: 5, extra_weapon_attack: 10, hp_regen: 320, mp_regen: 320, life_leech: 0.33, mana_leech: 0.33, freedeath: 1 } },
        { id: "37456", name: "Rich Ring", tier: "Legendary", weight: 80, stats: { extra_weapon_attack: 5, hp_regen: 50, mp_regen: 50, speed: 20 } }
      ]
    },
    ammo_slot: {
      label: "Ammo Slot",
      description: "Ammunition and special items for the ammo slot",
      items: [
        { id: "40736", name: "Diamond Arrow", tier: "Uncommon", weight: 80, attack: 37, weaponType: "ammunition" },
        { id: "40737", name: "Spectral Bolt", tier: "Uncommon", weight: 90, attack: 78, weaponType: "ammunition" },
        { id: "40683", name: "Blue Quiver", tier: "Uncommon", weight: 1700, container_size: 6 },
        { id: "40684", name: "Red Quiver", tier: "Uncommon", weight: 1700, container_size: 6 },
        { id: "10944", name: "Universal Tool", tier: "Uncommon", weight: 0, stats: { hp_regen: 5, mp_regen: 5, speed: 20 } },
        { id: "40964", name: "Tuning Fork", tier: "Uncommon", weight: 20, stats: { distance_fighting: 3, sword_fighting: 3, magic_level: 3, extra_weapon_attack: 2 } },
        { id: "41063", name: "Reduction Doll", tier: "Uncommon", weight: 20, stats: { damage_reduction: 2 } },
        { id: "40924", name: "Death Gaze", tier: "Uncommon", weight: 20, stats: { damage_reduction: 2, mana_rune_increase: 3, healing_rune_increase: 3 } },
        { id: "40963", name: "Lit Moon Mirror", tier: "Uncommon", weight: 1500, stats: { damage_increase: 2, mana_rune_increase: 3, critical_hit_chance: 2 } },
        { id: "10309", name: "Claw of The Noxious Spawn", tier: "Uncommon", weight: 1500, stats: { mana_rune_increase: 3, healing_rune_increase: 3 } },
        { id: "12424", name: "Ornamented Brooch", tier: "Uncommon", weight: 1070, stats: { damage_increase: 2 } },
        { id: "12667", name: "Phoenix Statue", tier: "Uncommon", weight: 840, stats: { max_health: 3, max_mana: 3 } },
        { id: "9955", name: "Vampiric Crest", tier: "Uncommon", weight: 500, stats: { critical_hit_chance: 2, critical_hit_damage: 5 } },
        { id: "25391", name: "Rift Lamp", tier: "Rare", weight: 890, stats: { sword_fighting: 5, extra_weapon_attack: 10 } },
        { id: "36282", name: "Ivory Lyre", tier: "Rare", weight: 890, stats: { magic_level: 5, extra_weapon_attack: 10 } },
        { id: "2361", name: "Frozen Starlight", tier: "Rare", weight: 890, stats: { attack_speed: 5, distance_fighting: 5, extra_weapon_attack: 10 } },
        { id: "36511", name: "Note Souls", tier: "Rare", weight: 890, stats: { max_health: 5, max_mana: 5, reduce_skill_loss: 10, extra_weapon_attack: 10 } },
        { id: "41280", name: "Compass Life", tier: "Legendary", weight: 890, stats: { reduce_skill_loss: 10, critical_hit_chance: 6, life_leech: 0.2, mana_leech: 0.2, extra_weapon_attack: 20 } },
        { id: "41307", name: "Archer Boy", tier: "Legendary", weight: 890, stats: { max_health: 10, max_mana: 10, distance_fighting: 5, dodge: 5, attack_speed: 5, extra_weapon_attack: 20 } },
        { id: "41313", name: "Mystic Power", tier: "Legendary", weight: 890, stats: { max_health: 7, max_mana: 15, magic_level: 5, critical_hit_chance: 3, extra_weapon_attack: 20 } },
        { id: "41279", name: "Valor Defender", tier: "Legendary", weight: 890, stats: { max_health: 15, max_mana: 7, sword_fighting: 5, life_leech: 0.2, mana_leech: 0.2, extra_weapon_attack: 35 } },
        { id: "21703", name: "Vanishing Eye", tier: "Rare", weight: 150, description: "mysterious eye gem that grants its wielder the power of invisibility for 5 seconds" },
        { id: "46295", name: "Packages Backpack", tier: "Uncommon", weight: 120 },
        { id: "38944", name: "Rich Bag", tier: "Uncommon", weight: 1500, stats: { death_protection: 2, holy_protection: 2, fire_protection: 2, ice_protection: 2, energy_protection: 2, earth_protection: 2 } }
      ]
    },
    charms: {
      label: "Charms",
      description: "Magical charm slots for special bonuses and effects",
      items: [
        { id: "45934", name: "Revive Doll", tier: "Uncommon", weight: 500, charm: 1, stats: { guardian: 1 } },
        { id: "40965", name: "Final Judgement", tier: "Uncommon", weight: 200, charm: 1, stats: { extra_weapon_attack: 5, speed: 20 } },
        { id: "41305", name: "Rich Doll", tier: "Legendary", weight: 5000, charm: 1, stats: { extra_weapon_attack: 10, distance_fighting: 2, sword_fighting: 2, magic_level: 2, max_health: 2, max_mana: 2 } },
        { id: "11144", name: "Nightmare Doll", tier: "Rare", weight: 1800, charm: 1, stats: { life_leech: 0.12, mana_leech: 0.06, damage_reduction: 2 } },
        { id: "13559", name: "Dread Doll", tier: "Uncommon", weight: 1800, charm: 1, stats: { critical_hit_chance: 2, critical_hit_damage: 5 } },
        { id: "41276", name: "Powerful Doll", tier: "Uncommon", weight: 500, charm: 1, stats: { healing_rune_increase: 5, max_health: 3, life_leech: 0.2, mana_leech: 0.06 } },
        { id: "33276", name: "Bone Fiddle", tier: "Uncommon", weight: 900, charm: 1, stats: { max_mana: 3, mana_rune_increase: 5, mana_leech: 0.2 } },
        { id: "26343", name: "Burnt Out Devourer Core", tier: "Rare", weight: 900, charm: 1, stats: { critical_hit_chance: 4, life_leech: 0.06, attack_speed: 6, mana_leech: 0.06 } },
        { id: "24684", name: "Noble Sword", tier: "Uncommon", weight: 900, charm: 1, stats: { distance_fighting: 5, sword_fighting: 5, healing_rune_increase: 3 } },
        { id: "27730", name: "Pinata Dragon", tier: "Uncommon", weight: 500, charm: 1, stats: { magic_level: 6, mana_rune_increase: 3 } },
        { id: "41022", name: "Lion Doll", tier: "Uncommon", weight: 500, charm: 1, stats: { max_health: 3, max_mana: 3 } },
        { id: "26342", name: "Devourer Core", tier: "Uncommon", weight: 100, charm: 1, stats: { hp_regen: 300, mp_regen: 300 } },
        { id: "42403", name: "Draptor Doll", tier: "Rare", weight: 100, charm: 1, stats: { extra_weapon_attack: 20, max_health: 6, max_mana: 6, critical_hit_chance: 3, distance_fighting: 5, magic_level: 5, sword_fighting: 5 } },
        { id: "41471", name: "Tentacle Lute (Charm)", tier: "Legendary", weight: 900, charm: 1, stats: { max_mana: 10, magic_level: 8, mana_rune_increase: 8, critical_hit_chance: 4, mana_leech: 5, extra_weapon_attack: 22, attack_speed: 4 } },
        { id: "41472", name: "Arodis Magical Board (Charm)", tier: "Legendary", weight: 900, charm: 1, stats: { max_health: 10, max_mana: 10, life_leech: 4, mana_leech: 4, damage_reduction: 4, dodge: 4, extra_weapon_attack: 22 } },
        { id: "41473", name: "Arbaziloth Santa Figure (Charm)", tier: "Legendary", weight: 950, charm: 1, stats: { max_health: 12, max_mana: 10, life_leech: 6, mana_leech: 6, attack_speed: 6, extra_weapon_attack: 28 } },
        { id: "41474", name: "Khufu Hand (Charm)", tier: "Legendary", weight: 1000, charm: 1, stats: { max_health: 16, max_mana: 16, damage_increase: 12, damage_reduction: 6, critical_hit_chance: 7, attack_speed: 7, distance_fighting: 8, sword_fighting: 8, magic_level: 8, extra_weapon_attack: 36 } }
      ]
    },
    backpack: {
      label: "Backpacks",
      description: "Equipment slots for carrying items with powerful bonuses",
      items: [
        { id: "2365", name: "Backpack of Holding", tier: "Uncommon", weight: 1500, container_size: 28, stats: { distance_fighting: 2, sword_fighting: 2, magic_level: 2 } },
        { id: "11242", name: "Damage Bag", tier: "Uncommon", weight: 800, container_size: 32, stats: { distance_fighting: 5, sword_fighting: 5, magic_level: 5 } },
        { id: "3939", name: "Protection Bag", tier: "Uncommon", weight: 800, container_size: 32, stats: { max_health: 3, max_mana: 3, damage_reduction: 2 } },
        { id: "11244", name: "Minotaur Backpack", tier: "Uncommon", weight: 800, container_size: 25, stats: { distance_fighting: 2, magic_level: 2, sword_fighting: 2 } },
        { id: "40972", name: "Bosses Bag Loot", tier: "Uncommon", weight: 800, container_size: 12 },
        { id: "40935", name: "Wolf Backpack", tier: "Rare", weight: 800, container_size: 32, stats: { hp_regen: 150, mp_regen: 150 } },
        { id: "40936", name: "Energetic Backpack", tier: "Rare", weight: 800, container_size: 32, stats: { attack_speed: 4 } },
        { id: "40937", name: "Ghost Backpack", tier: "Rare", weight: 800, container_size: 32, stats: { critical_hit_chance: 3, attack_speed: 5, extra_weapon_attack: 10 } },
        { id: "40938", name: "Festive Backpack", tier: "Rare", weight: 800, container_size: 32, stats: { hp_regen: 250, life_leech: 0.1, mana_leech: 0.1, mp_regen: 250 } },
        { id: "40939", name: "Winged Backpack", tier: "Rare", weight: 800, container_size: 32, stats: { attack_speed: 4, extra_weapon_attack: 10 } },
        { id: "40934", name: "Feedbag", tier: "Rare", weight: 800, container_size: 30, stats: { life_drain_protection: 0.06, distance_fighting: 2, magic_level: 2, sword_fighting: 2, max_health: 3, max_mana: 3 } },
        { id: "23666", name: "Glooth Backpack", tier: "Legendary", weight: 1800, container_size: 35, stats: { energy_protection: 3, extra_weapon_attack: 10, reduce_skill_loss: 10, max_health: 4, max_mana: 4 } },
        { id: "46299", name: "Arcane Backpack", tier: "Legendary", weight: 1800, container_size: 45, stats: { protection_all: 2, extra_weapon_attack: 20, critical_hit_chance: 5, critical_hit_damage: 10, magic_level: 8, damage_increase: 6 } },
        { id: "46297", name: "Ethereal Backpack", tier: "Legendary", weight: 1800, container_size: 45, stats: { protection_all: 2, extra_weapon_attack: 20, critical_hit_chance: 7, critical_hit_damage: 10, distance_fighting: 8, attack_speed: 6 } },
        { id: "46296", name: "Ironclad Backpack", tier: "Legendary", weight: 1800, container_size: 45, stats: { protection_all: 2, extra_weapon_attack: 30, critical_hit_chance: 3, critical_hit_damage: 7, sword_fighting: 8, damage_increase: 10 } },
        { id: "41475", name: "Cursed Crimsonevil Backpack", tier: "Legendary", weight: 2100, container_size: 52, stats: { absorption_all: 3, extra_weapon_attack: 22, critical_hit_chance: 6, critical_damage: 12, life_leech: 4, mana_leech: 4, max_health: 8, max_mana: 8 } },
        { id: "41476", name: "Draconic Backpack", tier: "Legendary", weight: 2300, container_size: 60, stats: { absorption_all: 4, extra_weapon_attack: 30, critical_hit_chance: 8, critical_damage: 16, distance_fighting: 10, sword_fighting: 10, damage_increase: 12, max_health: 10, max_mana: 10 } }
      ]
    }
  },
  weapons: {
    melee: {
      label: "Melee Weapons",
      items: [
        { id: "2392", name: "Fire Sword", tier: "Uncommon", weight: 2300, attack: 40, defense: 18, stats: {} },
        { id: "2432", name: "Fire Axe", tier: "Uncommon", weight: 4000, attack: 40, defense: 18, stats: {} },
        { id: "2436", name: "Skull Staff", tier: "Uncommon", weight: 1700, attack: 40, defense: 18, stats: {} },
        { id: "7406", name: "Blacksteel Sword", tier: "Uncommon", weight: 5900, attack: 55, defense: 22, stats: {} },
        { id: "7383", name: "Relic Sword", tier: "Uncommon", weight: 4200, attack: 60, defense: 20, stats: {} },
        { id: "7437", name: "Sapphire Hammer", tier: "Uncommon", weight: 12500, attack: 60, defense: 20, stats: {} },
        { id: "7456", name: "Noble Axe", tier: "Uncommon", weight: 9900, attack: 60, defense: 20, stats: {} },
        { id: "2400", name: "Magic Sword", tier: "Uncommon", weight: 4300, attack: 70, defense: 22, stats: { sword_fighting: 1, extra_weapon_attack: 2 } },
        { id: "2431", name: "Stonecutter Axe", tier: "Uncommon", weight: 9000, attack: 70, defense: 22, stats: { sword_fighting: 1, extra_weapon_attack: 2 } },
        { id: "2421", name: "Thunder Hammer", tier: "Uncommon", weight: 7000, attack: 70, defense: 22, stats: { sword_fighting: 1, extra_weapon_attack: 2 } },
        { id: "6528", name: "The Avenger", tier: "Uncommon", weight: 6400, attack: 85, defense: 28, stats: { sword_fighting: 2, extra_weapon_attack: 2 } },
        { id: "7435", name: "Impaler", tier: "Uncommon", weight: 6800, attack: 85, defense: 28, stats: { critical_hit_chance: 2 } },
        { id: "7427", name: "Chaos Mace", tier: "Uncommon", weight: 3100, attack: 85, defense: 28, stats: { attack_speed: 2 } },
        { id: "40822", name: "Rich Sword", tier: "Legendary", weight: 4500, attack: 150, defense: 40, stats: { sword_fighting: 5, damage_reduction: 2, extra_weapon_attack: 5 } },
        { id: "2390", name: "Magic Longsword", tier: "Legendary", weight: 50, attack: 180, defense: 42, stats: { sword_fighting: 7, damage_reduction: 2, extra_weapon_attack: 6 } },
        { id: "40824", name: "Rich Axe", tier: "Rare", weight: 4200, attack: 100, defense: 32, stats: { critical_hit_chance: 2 } },
        { id: "40823", name: "Rich Club", tier: "Rare", weight: 5900, attack: 100, defense: 32, stats: { attack_speed: 4 } },
        { id: "18465", name: "Shiny Blade", tier: "Rare", weight: 6400, attack: 150, defense: 40, stats: { damage_reduction: 1, sword_fighting: 6, extra_weapon_attack: 5 } },
        { id: "8924", name: "Hellforged Axe", tier: "Rare", weight: 5800, attack: 150, defense: 40, stats: { damage_reduction: 1, critical_hit_chance: 2 } },
        { id: "7414", name: "Abyss Hammer", tier: "Rare", weight: 7800, attack: 150, defense: 40, stats: { damage_reduction: 1, attack_speed: 6 } },
        { id: "2452", name: "Heavy Mace", tier: "Rare", weight: 6900, attack: 180, defense: 43, stats: { sword_fighting: 8, extra_weapon_attack: 5, damage_reduction: 2 } },
        { id: "8926", name: "Demonwing Axe", tier: "Rare", weight: 6800, attack: 180, defense: 43, stats: { damage_reduction: 2, critical_hit_chance: 2 } },
        { id: "8930", name: "Emerald Sword", tier: "Rare", weight: 3800, attack: 180, defense: 43, stats: { damage_reduction: 2, attack_speed: 8 } },
        { id: "41426", name: "Titan Wrath Sword", tier: "Legendary", weight: 1500, attack: 520, defense: 80, stats: { sword_fighting: 28, extra_weapon_attack: 25, max_health: 25, damage_reduction: 8 } },
        { id: "41436", name: "Titan Wrath Axe", tier: "Legendary", weight: 12000, attack: 520, defense: 80, stats: { extra_weapon_attack: 25, damage_reduction: 8, max_health: 25, critical_hit_chance: 5 } },
        { id: "41437", name: "Titan Wrath Club", tier: "Legendary", weight: 3200, attack: 520, defense: 80, stats: { extra_weapon_attack: 25, damage_reduction: 8, max_health: 25, attack_speed: 25 } },
        { id: "25926", name: "Red Mithril Sword", tier: "Legendary", weight: 1500, attack: 320, defense: 55, stats: { extra_weapon_attack: 15, sword_fighting: 9 } },
        { id: "25934", name: "Red Mithril Axe", tier: "Legendary", weight: 12000, attack: 320, defense: 55, stats: { extra_weapon_attack: 15, critical_hit_chance: 10 } },
        { id: "25942", name: "Red Mithril Hammer", tier: "Legendary", weight: 3200, attack: 320, defense: 55, stats: { extra_weapon_attack: 15, attack_speed: 15 } },
        { id: "8932", name: "The Calamity", tier: "Rare", weight: 1500, attack: 200, defense: 45, stats: { sword_fighting: 5, extra_weapon_attack: 5, damage_reduction: 2 } },
        { id: "15404", name: "Deepling Axe", tier: "Rare", weight: 1500, attack: 200, defense: 45, stats: { critical_hit_chance: 3, extra_weapon_attack: 5 } },
        { id: "8929", name: "The Stomper", tier: "Rare", weight: 1500, attack: 200, defense: 45, stats: { attack_speed: 10, extra_weapon_attack: 5 } },
        { id: "8925", name: "Solar Axe", tier: "Rare", weight: 11000, attack: 125, defense: 36, stats: { sword_fighting: 2, extra_weapon_attack: 3 } },
        { id: "8927", name: "Dark Trinity Mace", tier: "Rare", weight: 9200, attack: 125, defense: 36, stats: { critical_hit_chance: 2 } },
        { id: "8931", name: "The Epiphany", tier: "Rare", weight: 6150, attack: 125, defense: 36, stats: { attack_speed: 5 } },
        { id: "23548", name: "Semo Sword", tier: "Rare", weight: 2300, attack: 10, defense: 10, description: "This sword is made for Semo, and she knows how to use it" },
        { id: "41465", name: "Thorn Longsword", tier: "Rare", weight: 1500, attack: 380, defense: 60, stats: { sword_fighting: 12, extra_weapon_attack: 20, max_health: 5 } },
        { id: "41466", name: "Thorn Battleaxe", tier: "Rare", weight: 12000, attack: 380, defense: 60, stats: { extra_weapon_attack: 20, critical_hit_chance: 13, max_health: 5 } },
        { id: "41467", name: "Thorn Mace", tier: "Rare", weight: 3200, attack: 380, defense: 60, stats: { extra_weapon_attack: 20, attack_speed: 20, max_health: 5 } },
        { id: "41398", name: "Soulshade Sword", tier: "Legendary", weight: 1500, attack: 420, defense: 60, stats: { sword_fighting: 15, extra_weapon_attack: 25, max_health: 7 } },
        { id: "41397", name: "Soulshade Axe", tier: "Legendary", weight: 12000, attack: 420, defense: 60, stats: { extra_weapon_attack: 25, critical_hit_chance: 13, max_health: 7 } },
        { id: "41396", name: "Soulshade Mace", tier: "Legendary", weight: 3200, attack: 420, defense: 60, stats: { extra_weapon_attack: 25, attack_speed: 25, max_health: 7 } },
        { id: "38917", name: "Soulcutter", tier: "Legendary", weight: 1500, attack: 485, defense: 65, stats: { sword_fighting: 18, extra_weapon_attack: 30, max_health: 9 } },
        { id: "38919", name: "Soulbiter", tier: "Legendary", weight: 12000, attack: 485, defense: 65, stats: { extra_weapon_attack: 30, critical_hit_chance: 15, max_health: 9 } },
        { id: "38922", name: "Soulmaimer", tier: "Legendary", weight: 3200, attack: 485, defense: 65, stats: { extra_weapon_attack: 30, attack_speed: 25, max_health: 9 } },
        { id: "40907", name: "Violet Sword", tier: "Rare", weight: 1500, attack: 250, defense: 48, stats: { sword_fighting: 7, extra_weapon_attack: 10 } },
        { id: "40908", name: "Violet Axe", tier: "Rare", weight: 1500, attack: 250, defense: 48, stats: { critical_hit_chance: 5, extra_weapon_attack: 10 } },
        { id: "40909", name: "Violet Hammer", tier: "Rare", weight: 1500, attack: 250, defense: 48, stats: { attack_speed: 10, extra_weapon_attack: 15 } }
      ]
    },
    distance: {
      label: "Distance Weapons",
      items: [
        { id: "2455", name: "Crossbow", tier: "Uncommon", weight: 4000, attack: 55, stats: {} },
        { id: "8852", name: "The Devileye", tier: "Uncommon", weight: 4000, attack: 65, stats: {} },
        { id: "8849", name: "Modified Crossbow", tier: "Uncommon", weight: 3500, attack: 70, stats: { distance_fighting: 2, extra_weapon_attack: 2 } },
        { id: "5803", name: "Arbalest", tier: "Uncommon", weight: 9500, attack: 85, stats: { distance_fighting: 2, extra_weapon_attack: 2 } },
        { id: "8851", name: "Royal Crossbow", tier: "Uncommon", weight: 5200, attack: 110, stats: { distance_fighting: 4, extra_weapon_attack: 2 } },
        { id: "40848", name: "Rich Crossbow", tier: "Legendary", weight: 5200, attack: 190, stats: { distance_fighting: 6, extra_weapon_attack: 5, critical_hit_chance: 5, attack_speed: 4 } },
        { id: "8858", name: "Elethriel's Elemental Bow", tier: "Legendary", weight: 50, attack: 210, stats: { distance_fighting: 8, extra_weapon_attack: 5, critical_hit_chance: 5, attack_speed: 5 } },
        { id: "18453", name: "Crystal Crossbow", tier: "Rare", weight: 5500, attack: 180, stats: { distance_fighting: 5, extra_weapon_attack: 5, critical_hit_chance: 5, attack_speed: 4 } },
        { id: "25523", name: "Warsinger Bow", tier: "Rare", weight: 4500, attack: 200, stats: { distance_fighting: 7, extra_weapon_attack: 5, critical_hit_chance: 6, attack_speed: 4 } },
        { id: "41435", name: "Titan Wrath Bow", tier: "Legendary", weight: 12000, attack: 580, stats: { distance_fighting: 22, extra_weapon_attack: 25, max_health: 15, max_mana: 15, attack_speed: 25, critical_hit_chance: 9 } },
        { id: "8853", name: "The Ironworker", tier: "Rare", weight: 4500, attack: 140, stats: { distance_fighting: 5, extra_weapon_attack: 3, critical_hit_chance: 4, attack_speed: 4 } },
        { id: "30691", name: "Crossbow of Destruction", tier: "Rare", weight: 12000, attack: 360, stats: { distance_fighting: 10, extra_weapon_attack: 15, critical_hit_chance: 11, attack_speed: 15, max_health: 4, max_mana: 4 } },
        { id: "35228", name: "Cobra Crossbow", tier: "Rare", weight: 3500, attack: 225, stats: { distance_fighting: 5, extra_weapon_attack: 5, critical_hit_chance: 5, attack_speed: 6 } },
        { id: "8850", name: "Chain Bolter", tier: "Rare", weight: 4400, attack: 285, stats: { distance_fighting: 7, extra_weapon_attack: 8, critical_hit_chance: 8, attack_speed: 10 } },
        { id: "41469", name: "Thorn Spitter", tier: "Rare", weight: 12000, attack: 430, stats: { distance_fighting: 12, extra_weapon_attack: 20, max_health: 3, max_mana: 3, attack_speed: 15, critical_hit_chance: 15 } },
        { id: "41394", name: "Soulshade Spitter", tier: "Legendary", weight: 12000, attack: 490, stats: { distance_fighting: 15, extra_weapon_attack: 25, max_health: 5, max_mana: 5, attack_speed: 18, critical_hit_chance: 15 } },
        { id: "38924", name: "Soulpiercer", tier: "Legendary", weight: 12000, attack: 535, stats: { distance_fighting: 18, extra_weapon_attack: 30, max_health: 7, max_mana: 7, attack_speed: 25, critical_hit_chance: 15 } }
      ]
    },
    mage: {
      label: "Wands & Rods",
      items: [
        { id: "2190", name: "Wand of Vortex", tier: "Uncommon", weight: 100, attack: 48, stats: {} },
        { id: "2189", name: "Wand of Cosmic Energy", tier: "Uncommon", weight: 200, attack: 58, stats: {} },
        { id: "13880", name: "Shimmer Wand", tier: "Uncommon", weight: 200, attack: 65, stats: { extra_weapon_attack: 2 } },
        { id: "2184", name: "Crystal Wand", tier: "Uncommon", weight: 200, attack: 75, stats: { extra_weapon_attack: 2, magic_level: 1 } },
        { id: "18390", name: "Wand of Defiance", tier: "Uncommon", weight: 200, attack: 95, stats: { magic_level: 2, extra_weapon_attack: 2 } },
        { id: "40825", name: "Rich Wand", tier: "Legendary", weight: 200, attack: 170, stats: { magic_level: 3, extra_weapon_attack: 5, critical_hit_chance: 5, attack_speed: 4 } },
        { id: "7958", name: "Jester Wand", tier: "Legendary", weight: 50, attack: 190, stats: { magic_level: 6, extra_weapon_attack: 5, critical_hit_chance: 5, attack_speed: 6 } },
        { id: "7429", name: "Blessed Staff", tier: "Rare", weight: 200, attack: 165, stats: { magic_level: 5, extra_weapon_attack: 4, critical_hit_chance: 5, attack_speed: 5 } },
        { id: "7410", name: "Attunement Staff", tier: "Rare", weight: 200, attack: 190, stats: { magic_level: 6, extra_weapon_attack: 5, critical_hit_chance: 5, attack_speed: 5 } },
        { id: "41434", name: "Titan Wrath Wand", tier: "Legendary", weight: 200, attack: 560, stats: { magic_level: 22, extra_weapon_attack: 25, max_mana: 20, attack_speed: 25, critical_hit_chance: 6 } },
        { id: "25420", name: "Ferumbras' Staff", tier: "Rare", weight: 200, attack: 135, stats: { magic_level: 5, extra_weapon_attack: 3, attack_speed: 4 } },
        { id: "12327", name: "Novice's Arcane Staff", tier: "Rare", weight: 200, attack: 215, stats: { magic_level: 8, extra_weapon_attack: 5, critical_hit_chance: 6, attack_speed: 8 } },
        { id: "38925", name: "Soultainter", tier: "Legendary", weight: 200, attack: 510, stats: { magic_level: 18, extra_weapon_attack: 30, max_mana: 9, attack_speed: 18, critical_hit_chance: 12 } },
        { id: "41470", name: "Thorn Wand", tier: "Rare", weight: 200, attack: 405, stats: { magic_level: 12, extra_weapon_attack: 10, max_mana: 5, attack_speed: 10, critical_hit_chance: 10 } },
        { id: "41399", name: "Soulshade Wand", tier: "Legendary", weight: 200, attack: 460, stats: { magic_level: 15, extra_weapon_attack: 20, max_mana: 7, attack_speed: 13, critical_hit_chance: 12 } },
        { id: "38925", name: "Soul Tainter", tier: "Legendary", weight: 200, attack: 510, stats: { magic_level: 18, extra_weapon_attack: 30, max_mana: 9, attack_speed: 18, critical_hit_chance: 12 } },
        { id: "30692", name: "Wand of Destruction", tier: "Rare", weight: 200, attack: 350, stats: { magic_level: 10, extra_weapon_attack: 10, critical_hit_chance: 10, attack_speed: 10, max_mana: 5 } },
        { id: "38987", name: "Lion Wand", tier: "Rare", weight: 200, attack: 270, stats: { magic_level: 8, extra_weapon_attack: 8, critical_hit_chance: 5, attack_speed: 10 } },
        { id: "8920", name: "Crown Wand", tier: "Uncommon", weight: 725, attack: 0 },
        { id: "7438", name: "Crown Bow", tier: "Uncommon", weight: 2900, attack: 62 }
      ]
    }
  }
};

export default function ItemsPage() {
  return <ItemsClient itemData={itemData} />;
}
