export const knowledgeSourceRegistry = {
  officialCharacterManual: {
    id: 'official-character-manual',
    label: 'Official Tibia character manual',
    href: 'https://www.tibia.com/gameguides/?section=characters&subtopic=manual',
    authority: 'Official game documentation',
    scope: 'Character attributes, skills, soul points, and stamina behavior in the current official game.',
  },
  officialCombatManual: {
    id: 'official-combat-manual',
    label: 'Official Tibia combat manual',
    href: 'https://www.tibia.com/gameguides/?section=combat&subtopic=manual',
    authority: 'Official game documentation',
    scope: 'Combat controls, aggression marks, protection-zone blocks, and official-world PvP behavior.',
  },
  officialMagicManual: {
    id: 'official-magic-manual',
    label: 'Official Tibia magic manual',
    href: 'https://www.tibia.com/gameguides/?section=magic&subtopic=manual',
    authority: 'Official game documentation',
    scope: 'Current official spell learning, spoken casting, cooldown groups, magic-level progression, and rune behavior.',
  },
  officialSpellLibrary: {
    id: 'official-spell-library',
    label: 'Official Tibia spell library',
    href: 'https://www.tibia.com/library/?subtopic=spells',
    authority: 'Official game library',
    scope: 'Current official spell names, words, groups, types, level requirements, mana, premium status, and detailed spell profiles.',
  },
  officialCreatureLibrary: {
    id: 'official-creature-library',
    label: 'Official Tibia creature library',
    href: 'https://www.tibia.com/library/?subtopic=creatures',
    authority: 'Official game library',
    scope: 'Current official creature names, health, experience, resistance categories, status behavior, and named loot.',
  },
  tibiaDataTransport: {
    id: 'tibiadata-v4-transport',
    label: 'TibiaData v4 API documentation',
    href: 'https://docs.tibiadata.com/',
    authority: 'Open-source official-fansite transport',
    scope: 'Structured transport used to read public tibia.com library facts while retaining each official source URL and observation timestamp.',
  },
  tfsRelease: {
    id: 'tfs-1-6-release',
    label: 'The Forgotten Server 1.6 release',
    href: 'https://github.com/otland/forgottenserver/releases/tag/v1.6',
    authority: 'Primary open-source release',
    scope: 'Pins the Open Tibia reference profile used by the formulas and data tables on these pages.',
  },
  tfsExperience: {
    id: 'tfs-experience-source',
    label: 'TFS 1.6 level experience implementation',
    href: 'https://github.com/otland/forgottenserver/blob/v1.6/src/player.h#L143-L146',
    authority: 'Primary source code',
    scope: 'Cubic total-experience formula used by the TFS 1.6 player implementation.',
  },
  tfsVocation: {
    id: 'tfs-vocation-source',
    label: 'TFS 1.6 skill and magic-level requirements',
    href: 'https://github.com/otland/forgottenserver/blob/v1.6/src/vocation.cpp#L139-L155',
    authority: 'Primary source code',
    scope: 'Skill bases, vocation multipliers, and mana-spent progression formula.',
  },
  tfsVocationData: {
    id: 'tfs-vocation-data',
    label: 'TFS 1.6 vocation configuration',
    href: 'https://github.com/otland/forgottenserver/blob/v1.6/data/XML/vocations.xml',
    authority: 'Primary configuration data',
    scope: 'Default health, mana, capacity, regeneration, skill, and magic progression multipliers by vocation.',
  },
  tfsDefense: {
    id: 'tfs-defense-source',
    label: 'TFS 1.6 player armor and defense calculation',
    href: 'https://github.com/otland/forgottenserver/blob/v1.6/src/player.cpp#L320-L395',
    authority: 'Primary source code',
    scope: 'Equipment slots, shield selection, defense skill, fight-mode factor, and vocation multipliers.',
  },
  tfsBlocking: {
    id: 'tfs-blocking-source',
    label: 'TFS 1.6 block and armor roll implementation',
    href: 'https://github.com/otland/forgottenserver/blob/v1.6/src/creature.cpp#L850-L889',
    authority: 'Primary source code',
    scope: 'Defense and armor random-reduction ranges, immunity checks, and full-block results.',
  },
  tfsResistance: {
    id: 'tfs-resistance-source',
    label: 'TFS 1.6 equipment resistance implementation',
    href: 'https://github.com/otland/forgottenserver/blob/v1.6/src/player.cpp#L1957-L2023',
    authority: 'Primary source code',
    scope: 'Sequential percentage absorption, charge consumption, field absorption, and resistance bypass behavior.',
  },
  tfsMonsterResistance: {
    id: 'tfs-monster-resistance-source',
    label: 'TFS 1.6 monster resistance implementation',
    href: 'https://github.com/otland/forgottenserver/blob/v1.6/src/monster.cpp#L598-L620',
    authority: 'Primary source code',
    scope: 'How positive and negative monster element percentages modify incoming damage.',
  },
  tfsCritical: {
    id: 'tfs-critical-source',
    label: 'TFS 1.6 critical-hit implementation',
    href: 'https://github.com/otland/forgottenserver/blob/v1.6/src/combat.cpp#L795-L820',
    authority: 'Primary source code',
    scope: 'Critical chance, extra-damage amount, PvP reduction order, and excluded damage origins for targeted combat.',
  },
  tfsStaminaUse: {
    id: 'tfs-stamina-use',
    label: 'TFS 1.6 stamina experience event',
    href: 'https://github.com/otland/forgottenserver/blob/v1.6/data/scripts/events/player/default_onGainExperience.lua',
    authority: 'Primary server script',
    scope: 'Stamina consumption and the 150%, 100%, and 50% experience bands.',
  },
  tfsStaminaRegen: {
    id: 'tfs-stamina-regeneration',
    label: 'TFS 1.6 stamina regeneration script',
    href: 'https://github.com/otland/forgottenserver/blob/v1.6/data/creaturescripts/scripts/regenerate_stamina.lua',
    authority: 'Primary server script',
    scope: 'Offline delay, normal-band recovery, bonus-band recovery, and the 42-hour cap.',
  },
  tfsConfiguration: {
    id: 'tfs-default-configuration',
    label: 'TFS 1.6 default server configuration',
    href: 'https://github.com/otland/forgottenserver/blob/v1.6/config.lua.dist',
    authority: 'Primary configuration data',
    scope: 'World type, protection level, frag thresholds, PvP timers, rates, and stamina settings.',
  },
  tfsDragon: {
    id: 'tfs-dragon-data',
    label: 'TFS 1.6 Dragon definition',
    href: 'https://github.com/otland/forgottenserver/blob/v1.6/data/monster/monsters/dragon.xml',
    authority: 'Primary monster data',
    scope: 'Reference health, experience, attacks, defenses, resistances, immunities, behavior flags, and loot.',
  },
  tfsDemon: {
    id: 'tfs-demon-data',
    label: 'TFS 1.6 Demon definition',
    href: 'https://github.com/otland/forgottenserver/blob/v1.6/data/monster/monsters/demon.xml',
    authority: 'Primary monster data',
    scope: 'Reference health, experience, attacks, defenses, resistances, immunities, summons, and loot.',
  },
  tfsMagicPlateArmor: {
    id: 'tfs-magic-plate-armor-data',
    label: 'TFS 1.6 Magic Plate Armor definition',
    href: 'https://github.com/otland/forgottenserver/blob/v1.6/data/items/items.xml#L3865-L3869',
    authority: 'Primary item data',
    scope: 'Reference item identifier, armor value, weight, and equipment slot.',
  },
  tfsItems: {
    id: 'tfs-items-data',
    label: 'TFS 1.6 item definitions',
    href: 'https://github.com/otland/forgottenserver/blob/v1.6/data/items/items.xml',
    authority: 'Primary item data',
    scope: 'Item identifiers, slots, attack, defense, armor, weight, abilities, requirements, and decay attributes.',
  },
  tfsSpells: {
    id: 'tfs-spell-data',
    label: 'TFS 1.6 spell registry',
    href: 'https://github.com/otland/forgottenserver/blob/v1.6/data/spells/spells.xml',
    authority: 'Primary spell data',
    scope: 'Instant and rune spell names, words, level, magic level, mana, soul, cooldown group, aggression, and script bindings.',
  },
  tfsSpellEngine: {
    id: 'tfs-spell-engine',
    label: 'TFS 1.6 spell execution implementation',
    href: 'https://github.com/otland/forgottenserver/blob/v1.6/src/spells.cpp',
    authority: 'Primary source code',
    scope: 'Spell requirement checks, cooldowns, target handling, resource costs, protection-zone behavior, and execution.',
  },
  tfsQuestRegistry: {
    id: 'tfs-quest-registry',
    label: 'TFS 1.6 quest registration example',
    href: 'https://github.com/otland/forgottenserver/blob/v1.6/data/scripts/quests/%23example.lua',
    authority: 'Primary quest data',
    scope: 'The supported TFS 1.6 quest registration structure for quest names, storage ranges, missions, descriptions, and completion state.',
  },
  tfsLootScale: {
    id: 'tfs-loot-scale',
    label: 'TFS 1.6 loot chance scale',
    href: 'https://github.com/otland/forgottenserver/blob/v1.6/src/monsters.h#L13',
    authority: 'Primary source code',
    scope: 'Defines the 100,000-point base chance scale used by monster loot entries.',
  },
};

export function pickKnowledgeSources(...keys) {
  return keys.map((key) => {
    const source = knowledgeSourceRegistry[key];
    if (!source) throw new Error(`Unknown knowledge source: ${key}`);
    return source;
  });
}
